"""
export_static.py — Build a static, GitHub Pages–hostable snapshot of TasteScope.

GitHub Pages can't run Python, so this script pre-computes everything the
frontend needs by running the SAME TasteEngine the Flask app uses, then writes
a fully self-contained `docs/` folder:

    docs/
      index.html            (asset paths rewritten to relative)
      css/  ...             (copied from static/css)
      js/   ...             (copied from static/js)
      data/
        config.json         (browser uses this to detect "static mode")
        api/                (pre-computed JSON for every read-only endpoint)
          stats.json  blind-spots.json  favorite-artists.json
          constellation.json  evolution.json  recommendations.json
          weekly-discovery.json  challenges.json  challenges-opposite.json
          backfill-preview.json  uncategorized-breakdown.json  ban-list.json
          spotify-status.json  songs.json  (full dump — client-side paging/search)

The frontend keeps calling the same `/api/...` paths; a small shim in
`static/js/utils.js` transparently maps them to these files when it detects
`data/config.json`. Read-only actions (add/rate/backfill/ban edits) are
disabled with a friendly notice.

Usage (from the project root):

    python scripts/export_static.py                 # writes ./docs
    python scripts/export_static.py --out site/     # custom output dir

Then deploy `docs/` — either commit it and use branch-based Pages, or (better)
push and let .github/workflows/deploy-pages.yml rebuild + deploy automatically.
"""
import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.taste_engine import TasteEngine  # noqa: E402

DEFAULT_CSV = ROOT / "data" / "posts_tails.csv"
API_DIR_NAME = "data/api"
MARKER = ".static-export"  # marks a dir as a previous build (safety guard)


def _write_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  ✓ {path.relative_to(path.parents[1])}")


def export_static(engine: TasteEngine | None = None, out_dir: str = "docs") -> Path:
    """Build the static snapshot. Returns the output directory."""
    engine = engine or TasteEngine(str(DEFAULT_CSV))
    out = Path(out_dir).resolve()

    # Safety: never let a typo'd --out clobber the project or arbitrary folders.
    # NOTE: out.parents holds out's ANCESTORS — we must refuse only when out IS
    # the project root or sits ABOVE it (e.g. --out .. or --out C:/). In-project
    # outputs like docs/ or site/ are the normal, allowed case.
    if out == ROOT or out in ROOT.parents:
        raise ValueError(
            f"Refusing to export into {out}: would clobber the project root or a parent directory."
        )
    if out.exists():
        has_content = any(out.iterdir()) if out.is_dir() else True
        if has_content and not (out / MARKER).is_file():
            raise ValueError(
                f"Refusing to overwrite {out}: it is not a previous static export "
                f"(missing {MARKER} marker). Pick a different --out or remove it manually."
            )
        if has_content:
            shutil.rmtree(out)
    # exist_ok=True: reusing a pre-existing EMPTY dir is fine (we only reached
    # this point when it has no content or the marker check passed).
    out.mkdir(parents=True, exist_ok=True)
    (out / MARKER).write_text("generated by scripts/export_static.py", encoding="utf-8")

    print(f"Exporting static snapshot -> {out}")

    # 1. HTML — rewrite absolute asset paths to relative so the site works
    #    under any GitHub Pages subpath (e.g. /song_project/).
    html = (ROOT / "templates" / "index.html").read_text(encoding="utf-8")
    html = html.replace('href="/css/', 'href="css/').replace('src="/js/', 'src="js/')
    (out / "index.html").write_text(html, encoding="utf-8")
    print("  ✓ index.html (paths → relative)")

    # 2. CSS + JS
    shutil.copytree(ROOT / "static" / "css", out / "css")
    shutil.copytree(ROOT / "static" / "js", out / "js")
    print("  ✓ css/  ✓ js/")

    # 3. Full songs dump — one row per CSV entry (including unrated) so the
    #    browser shim can serve BOTH /api/songs (rated-only, matching the Flask
    #    endpoint) and /api/search-history (all rows) entirely client-side.
    songs = [
        {
            "title": r.get("title", ""),
            "rating": int(r["rating"]) if r.get("rating") else None,
            "date": r.get("date", ""),
            "preview": (r.get("tail") or "").replace("\n", " "),
        }
        for r in engine.rows
    ]

    snapshots = {
        "stats.json": engine.get_stats(),
        "blind-spots.json": engine.get_blind_spots(),
        "favorite-artists.json": engine.get_favorite_artists(),
        "constellation.json": engine.get_constellation(),
        "evolution.json": engine.get_evolution(),
        "recommendations.json": engine.get_recommendations(),
        "weekly-discovery.json": engine.get_weekly_discovery(),
        "challenges.json": engine.get_challenges(count=24, mode="outside_zone"),
        "challenges-opposite.json": engine.get_challenges(count=24, mode="opposite_taste"),
        "backfill-preview.json": engine.backfill_ratings(preview=True, method="all"),
        "uncategorized-breakdown.json": engine.get_uncategorized_breakdown(),
        "ban-list.json": engine.ban_list,
        "spotify-status.json": {
            "available": False,
            "message": "Read-only snapshot — Spotify API is not available. Use the Listen button for a direct Spotify search.",
        },
        "songs.json": {"songs": songs, "total": len(songs)},
    }

    # 3.5 Annotate recommendations/weekly/challenges with listened state from
    #     the live data/listened.json (best-effort snapshot of what's listened).
    try:
        _listened_raw = json.loads((ROOT / "data" / "listened.json").read_text(encoding="utf-8"))
        _store = _listened_raw.get("listened", {}) if isinstance(_listened_raw, dict) else {}
        _listened_sigs = set(_store.keys()) if isinstance(_store, dict) else set()
    except (FileNotFoundError, json.JSONDecodeError):
        _listened_sigs = set()

    def _sig(artist, song):
        return TasteEngine._normalize_sig(f"{artist} {song}")

    for cat_data in snapshots["recommendations.json"].values():
        for rec in cat_data.get("recommendations", []):
            rec["listened"] = _sig(rec.get("artist", ""), rec.get("song", "")) in _listened_sigs
    for pick in snapshots["weekly-discovery.json"].get("picks", []):
        pick["listened"] = _sig(pick.get("artist", ""), pick.get("song", "")) in _listened_sigs
    for challenge_file in ("challenges.json", "challenges-opposite.json"):
        for c in snapshots[challenge_file].get("challenges", []):
            c["listened"] = _sig(c.get("artist", ""), c.get("song", "")) in _listened_sigs

    for name, data in snapshots.items():
        _write_json(out / API_DIR_NAME / name, data)

    # 4. Config — lets the browser shim detect static mode on load.
    _write_json(
        out / "data" / "config.json",
        {
            "mode": "static",
            "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "counts": {
                "entries": len(engine.rows),
                "rated": len(engine.ratings),
                "songs_dumped": len(songs),
                "artists": len(getattr(engine, "artist_index", {})),
            },
        },
    )

    print(f"Done — {len(snapshots) + 1} data files. Open {out / 'index.html'} or deploy {out} to GitHub Pages.")
    return out


if __name__ == "__main__":
    # Windows consoles default to cp1252 and choke on Unicode arrows in prints
    # (same fix app.py uses).
    if hasattr(sys.stdout, "reconfigure"):
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except Exception:
            pass

    parser = argparse.ArgumentParser(description="Build static GitHub Pages snapshot.")
    parser.add_argument("--out", default="docs", help="Output directory (default: docs)")
    args = parser.parse_args()
    export_static(out_dir=args.out)
