#!/usr/bin/env python3
"""Batch 7: More known artists from unmapped list."""

import json
import os

COUNTRY_MAP = {
    # Real artists still unmapped
    'Michael Bublé': 'CA', 'Beyoncé': 'US', 'Auli\'i Cravalho': 'US',
    'Daniel Bélanger': 'CA', 'Arwen\'s Vigil': 'NZ',
    'spice girls': 'GB', 'We the kings': 'US', 'ZAYDE WØLF': 'US',
    'Måns Zelmerlöw': 'SE', 'Salvador Sobral': 'PT',
    'Raphael Gualazzi': 'IT', 'Thomas Jack': 'AU',
    'Dami Im': 'AU', 'Lordi': 'FI', 'Ylvis': 'NO',
    'Manic Drive': 'CA', 'Nena': 'DE', 'Vanessa Mae': 'SG',
    'Jake Paul': 'US', 'Lilly Wood & The Prick and Robin Schulz': 'FR',
    'Sigma ft. Birdy': 'GB', 'Lifehouse feat. Natasha Bedingfield': 'US',
    'Jason Mraz & Colbie Caillat': 'US', 'Pitbull ft. T-Pain': 'US',
    'Marshmello & Anne-Marie': 'GB', 'Dan + Shay, Justin Bieber': 'US',
    'Calvin Harris, Dua Lipa': 'GB', 'Jon Schmidt & Steven Sharp Nelson': 'US',
    'Mørland & Debrah Scarlett': 'NO', 'Farid Mammadov': 'AZ',
    'Joseph Vincent': 'US', 'Remady & Manu-L': 'CH',
    'Monty Are I': 'US', 'Bastian Baker & Yves Larock': 'CH',
    'Daniel Rosty & Sash_S': 'US', 'Dionesium x Mr. Chris': 'US',
    'Дon\'t You Forget About Me': 'GB', 'Little Talks': 'IS',
    ' clocks and clouds': 'DE', 'Brave Enough': 'US',
    'Voltaire, 2007': 'US',
    # More real artists
    'Beach Bunny': 'US', 'Barenaked Ladies': 'CA',
    'Bag Raiders': 'AU', 'Bahari': 'US', 'Barlow Girl': 'US',
    'Baz Luhrmann': 'AU', 'Belinda Carlisle': 'US',
    'Belot': 'FR', 'Blackalicious': 'US', 'Blackbriar': 'NL',
    'Blackbox Blitz': 'US', 'Blind Tyler': 'US',
    'Blossom Dearie': 'US', 'Bond': 'GB', 'Bones': 'US',
    'Brat': 'US', 'Bryce Vine': 'US', 'Burak Yeter': 'TR',
    'Candy Dulfer': 'NL', 'Carole King': 'US', 'Cassadee Pope': 'US',
    'Celeste': 'GB', 'Chameleon Circuit': 'GB',
    'Charly García': 'AR', 'Chelsea Jade': 'NZ',
    'Chelsea Wolfe': 'US', 'Chris Cornell': 'US',
    'Chris Lane': 'US', 'Christine Welch': 'US',
    'Cindy Morgan': 'US', 'Citizen Way': 'US',
    'Claire Rosinkranz': 'US', 'Coeur De Pirate': 'CA',
    'Courage My Love': 'CA', 'Crash Adams': 'CA',
    'Deerhoof': 'US', 'Deftones': 'US', 'Denzel Curry': 'US',
    "Destiny's Child": 'US', 'Dimash Kudaibergen': 'KZ',
    'Dodie Clark': 'GB', 'Dominic Fike': 'US', 'Dorothy': 'US',
    'Edward Sharpe & The Magnetic Zeros': 'US',
    'Ella Eyre': 'GB', 'Elmiene': 'GB', 'Elohim': 'US',
    'Emmelie de Forest': 'DK', 'Eric Clapton': 'GB',
    'Estelle': 'GB', 'Exuma': 'BS', 'Faun': 'DE',
    'Farid Mammadov': 'AZ', 'FLO': 'GB',
    'George Ezra': 'GB', 'Gnarls Barkley': 'US',
    'Gregorian': 'DE', 'Guster': 'US', 'Halsey': 'US',
    'Hans Zimmer': 'DE', 'Hayley Kiyoko': 'US',
    'Hillsong Worship': 'AU', 'Imagine Dragons': 'US',
    'Irma Thomas': 'US', 'J Balvin': 'CO',
    'Jeff Buckley': 'US', 'Joji': 'JP',
    'Jonas Blue': 'GB', 'Jonas Brothers': 'US', 'Joy Division': 'GB',
    'Judah & the Lion': 'US', 'Justice': 'FR',
    'Kacey Musgraves': 'US', 'Kat Graham': 'US',
    'Kaytranada': 'CA', 'Kero Kero Bonito': 'GB',
    'Kevin MacLeod': 'US', 'Kid Cudi': 'US', 'Killers': 'US',
    'Kings of Leon': 'US', 'Kodaline': 'IE', 'Kygo': 'NO',
    'Lauv': 'US', 'Leon Bridges': 'US', 'Leonard Cohen': 'CA',
    'Lights': 'CA', 'Lizzo': 'US', 'Lorde': 'NZ',
    'Louis Tomlinson': 'GB', 'Lucas Graham': 'DK',
    'Luis Fonsi': 'PR', 'M.I.A.': 'GB', 'M83': 'FR',
    'Mac DeMarco': 'CA', 'Maggie Rogers': 'US',
    'Major Lazer': 'US', 'Mark Ronson': 'GB',
    'Marshmello': 'US', 'Matt Maeson': 'US',
    'Meghan Trainor': 'US', 'Metro Station': 'US',
    'Moby': 'US', 'Mumford & Sons': 'GB',
    'NF': 'US', 'Neiked': 'SE', 'Niall Horan': 'IE',
    'Nicki Minaj': 'TT', 'Niki': 'ID', 'Ofenbach': 'FR',
    'Omar Apollo': 'US', 'Palaye Royale': 'CA',
    'Passion Pit': 'US', 'Phoebe Ryan': 'US',
    'Phum Viphurit': 'TH', 'Porter Robinson': 'US',
    'Post Malone': 'US', 'Quinn XCII': 'US', 'R3HAB': 'NL',
    'Radiohead': 'GB', 'Rainbow Kitten Surprise': 'US',
    'Rex Orange County': 'GB', 'Rita Ora': 'GB',
    'Robin Schulz': 'DE', 'Royal Blood': 'GB',
    'Run the Jewels': 'US', 'Sam Fischer': 'AU',
    'Sam Smith': 'GB', 'Selena Gomez': 'US',
    'Shawn Mendes': 'CA', 'Sleeping At Last': 'US',
    "Snail's House": 'JP', 'Sofi Tukker': 'US',
    'Son Lux': 'US', 'St. Lucia': 'ZA',
    'Steam Powered Giraffe': 'US', 'Stray Kids': 'KR',
    'Sufjan Stevens': 'US', 'Summer Walker': 'US',
    'T-Pain': 'US', 'Tash Sultana': 'AU',
    'Taylor Swift': 'US', 'The 1975': 'GB',
    'The Antlers': 'US', 'The Band CAMINO': 'US',
    'The Black Keys': 'US', 'The Chainsmokers': 'US',
    'The Drums': 'US', 'The Fray': 'US', 'The Game': 'US',
    'The Ink Spots': 'US', 'The Japanese House': 'GB',
    'The Kinks': 'GB', 'The Lumineers': 'US',
    'The Naked and Famous': 'NZ', 'The Neighbourhood': 'US',
    'The Paper Kites': 'AU', 'The Walters': 'US',
    'The xx': 'GB', 'Thrice': 'US', 'Tom Odell': 'GB',
    'Tones and I': 'AU', 'Twenty One Pilots': 'US',
    'Two Door Cinema Club': 'GB', 'Vampire Weekend': 'US',
    'Walk The Moon': 'US', 'Weezer': 'US',
    'Wolf Alice': 'GB', 'Yungblud': 'GB',
    'Zedd': 'DE', 'ZHU': 'US',
    'Agnes Obel': 'DK', 'Alt-J': 'GB', 'Amaarae': 'GH',
    'Aphex Twin': 'GB', 'Arctic Monkeys': 'GB',
    'Balthazar': 'BE', 'Beach House': 'US', 'Beck': 'US',
    'Ben Howard': 'GB', 'Billie Eilish': 'US', 'Björk': 'IS',
    'Bones UK': 'GB', 'Bon Iver': 'US', 'Bonobo': 'GB',
    'Brockhampton': 'US', 'Cage the Elephant': 'US',
    'CamelPhat': 'GB', 'Cashmere Cat': 'NO',
    'Childish Gambino': 'US', 'Clairo': 'US',
    'Dua Lipa': 'GB', 'Foals': 'GB', 'Glass Animals': 'GB',
    'Hozier': 'IE', 'IDLES': 'GB', 'Jai Wolf': 'US',
    'JPEGMAFIA': 'US', 'Kali Uchis': 'US',
    'Kenny Beats': 'US', 'King Princess': 'US',
    'LANY': 'US', 'Mac Miller': 'US', 'Mitski': 'US',
    'Nao': 'GB', 'Nothing But Thieves': 'GB',
    'Parcels': 'AU', 'Phoebe Bridgers': 'US',
    'Pink Sweat$': 'US', 'Real Estate': 'US',
    'Ruel': 'AU', 'SZA': 'US', 'Sam Fender': 'GB',
    'Tame Impala': 'AU', 'Thundercat': 'US',
    'Turnstile': 'US', 'Wet Leg': 'GB', 'Yves Tumor': 'US',
    # Eurovision/misc
    'Salvador Sobral': 'PT', 'Raphael Gualazzi': 'IT',
    'Dami Im': 'AU', 'Lordi': 'FI', 'Ylvis': 'NO',
    'Manic Drive': 'CA', 'Nena': 'DE',
    # More from unmapped
    'Birdy': 'GB', 'Billy Ocean': 'GB',
    'Bobby McFerrin': 'US', 'Bryce Vine': 'US',
    'Calvin Harris': 'GB', 'Candy Dulfer': 'NL',
    'Carole King': 'US', 'Cassadee Pope': 'US',
    'Celeste': 'GB', 'Chameleon Circuit': 'GB',
    'Chelsea Jade': 'NZ', 'Chelsea Wolfe': 'US',
    'Chris Cornell': 'US', 'Chris Lane': 'US',
    'Citizen Way': 'US', 'Claire Rosinkranz': 'US',
    'Coeur De Pirate': 'CA', 'Courage My Love': 'CA',
    'Crash Adams': 'CA', 'Deerhoof': 'US',
    'Deftones': 'US', 'Denzel Curry': 'US',
    "Destiny's Child": 'US', 'Dimash Kudaibergen': 'KZ',
    'Dodie Clark': 'GB', 'Dominic Fike': 'US',
    'Edward Sharpe & The Magnetic Zeros': 'US',
    'Ella Eyre': 'GB', 'Eric Clapton': 'GB',
    'Estelle': 'GB', 'Faun': 'DE',
    'George Ezra': 'GB', 'Gnarls Barkley': 'US',
    'Halsey': 'US', 'Hans Zimmer': 'DE',
    'Hayley Kiyoko': 'US', 'Hillsong Worship': 'AU',
    'Imagine Dragons': 'US', 'J Balvin': 'CO',
    'Jeff Buckley': 'US', 'Joji': 'JP',
    'Jonas Brothers': 'US', 'Joy Division': 'GB',
    'Kacey Musgraves': 'US', 'Kaytranada': 'CA',
    'Kid Cudi': 'US', 'Kings of Leon': 'US',
    'Kodaline': 'IE', 'Kygo': 'NO',
    'Lauv': 'US', 'Leon Bridges': 'US',
    'Leonard Cohen': 'CA', 'Lights': 'CA',
    'Lizzo': 'US', 'Lorde': 'NZ',
    'Louis Tomlinson': 'GB', 'Lucas Graham': 'DK',
    'Luis Fonsi': 'PR', 'M83': 'FR',
    'Mac DeMarco': 'CA', 'Maggie Rogers': 'US',
    'Mark Ronson': 'GB', 'Marshmello': 'US',
    'Meghan Trainor': 'US', 'Moby': 'US',
    'Mumford & Sons': 'GB', 'NF': 'US',
    'Niall Horan': 'IE', 'Nicki Minaj': 'TT',
    'Omar Apollo': 'US', 'Palaye Royale': 'CA',
    'Passion Pit': 'US', 'Phum Viphurit': 'TH',
    'Porter Robinson': 'US', 'Post Malone': 'US',
    'R3HAB': 'NL', 'Radiohead': 'GB',
    'Rex Orange County': 'GB', 'Rita Ora': 'GB',
    'Robin Schulz': 'DE', 'Royal Blood': 'GB',
    'Run the Jewels': 'US', 'Sam Smith': 'GB',
    'Selena Gomez': 'US', 'Shawn Mendes': 'CA',
    'Sleeping At Last': 'US', "Snail's House": 'JP',
    'Son Lux': 'US', 'Stray Kids': 'KR',
    'Sufjan Stevens': 'US', 'T-Pain': 'US',
    'Tash Sultana': 'AU', 'Taylor Swift': 'US',
    'The 1975': 'GB', 'The Black Keys': 'US',
    'The Chainsmokers': 'US', 'The Drums': 'US',
    'The Fray': 'US', 'The Japanese House': 'GB',
    'The Kinks': 'GB', 'The Lumineers': 'US',
    'The Naked and Famous': 'NZ', 'The Neighbourhood': 'US',
    'The xx': 'GB', 'Thrice': 'US', 'Tom Odell': 'GB',
    'Tones and I': 'AU', 'Twenty One Pilots': 'US',
    'Two Door Cinema Club': 'GB', 'Vampire Weekend': 'US',
    'Walk The Moon': 'US', 'Weezer': 'US',
    'Wolf Alice': 'GB', 'Yungblud': 'GB',
    'Zedd': 'DE', 'ZHU': 'US',
    'Aphex Twin': 'GB', 'Arctic Monkeys': 'GB',
    'Beach House': 'US', 'Beck': 'US',
    'Ben Howard': 'GB', 'Billie Eilish': 'US',
    'Björk': 'IS', 'Bon Iver': 'US', 'Bonobo': 'GB',
    'Childish Gambino': 'US', 'Clairo': 'US',
    'Dua Lipa': 'GB', 'Foals': 'GB',
    'Glass Animals': 'GB', 'Hozier': 'IE',
    'IDLES': 'GB', 'Kali Uchis': 'US',
    'Mac Miller': 'US', 'Mitski': 'US',
    'Nothing But Thieves': 'GB', 'Parcels': 'AU',
    'Phoebe Bridgers': 'US', 'Real Estate': 'US',
    'Ruel': 'AU', 'SZA': 'US', 'Sam Fender': 'GB',
    'Tame Impala': 'AU', 'Thundercat': 'US',
    'Turnstile': 'US', 'Wet Leg': 'GB', 'Yves Tumor': 'US',
}

CACHE_PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'artist_country_cache.json')

def main():
    cache = json.load(open(CACHE_PATH, 'r', encoding='utf-8'))
    added = 0
    for artist, code in COUNTRY_MAP.items():
        if artist not in cache or not cache[artist]:
            cache[artist] = code
            added += 1

    with open(CACHE_PATH, 'w', encoding='utf-8') as f:
        json.dump(cache, f, indent=2, ensure_ascii=False)

    mapped = sum(1 for v in cache.values() if v)
    print(f"Added {added} new mappings")
    print(f"Total cached: {len(cache)}")
    print(f"With country: {mapped}")

if __name__ == '__main__':
    main()
