#!/usr/bin/env python3
"""Comprehensive seed of all remaining identifiable artists + mark song titles."""
import json

CACHE_PATH = 'data/artist_country_cache.json'
with open(CACHE_PATH, 'r', encoding='utf-8') as f:
    cache = json.load(f)

# Seed remaining real artists
final_seed = {
    "Auli'i Cravalho": 'US', 'BTOB': 'KR', 'IU': 'KR', 'ENHYPEN': 'KR',
    'S3RL': 'GB', 'Magic!': 'CA', 'The Piano Guys': 'US', 'Callysta': 'ID',
    'Lindsey Stirling and William Joseph': 'US', 'Lindsey Stirling and Alex Aris': 'US',
    'Dan \u2013 Shay': 'US', 'Rina Sawayama': 'JP', 'Polo G': 'US',
    'IDKHOW BUT THEY FOUND ME': 'US',
    'I DONT KNOW HOW BUT THEY FOUND ME, Tessa Violet': 'US',
    'Sia, Diplo, Labrinth': 'AU', 'Karan Aujla/Desi Crew': 'CA',
    'Edward Sharpe': 'US', 'The Magnetic Zeros': 'US',
    'Yuki Kajiura': 'JP', 'Masayoshi Takanaka': 'JP',
    'Meekakitty': 'CA', 'heyhihello': 'US',
    'Paul Anka and Odia Coates': 'CA', 'Isaac Hayes w/The Bar-Kays': 'US',
    'Ryan Lewis': 'US', 'Stone Poneys': 'US', 'Siobhan Miller': 'GB',
    'Bria Lee': 'US', 'Jimi Cravity': 'KR', 'Steffany Gretzinger': 'US',
    'Bobby Strand': 'US', 'Hyde': 'JP', 'Boyinaband': 'GB',
    'Sufjan Stevens': 'US', 'au/ra': 'GB', 'Rosa Walton': 'GB',
    'Hallie Coggins': 'GB', 'Manu-L': 'CA', 'Jayn': 'JP',
    'Watanabe Yasushi': 'JP', 'Nena': 'DE', 'Chubby Checker': 'US',
    'Yoko Takahashi': 'JP', 'DMC': 'US', 'London grammar': 'GB',
    'black pistol fire': 'US', 'will i am': 'US', 'Sly': 'US',
    'The Family Stone': 'US', 'EMI//NOVA': 'US', 'Nolimiter': 'US',
    'Troy Young': 'US', 'Silver Maple': 'JP', 'Godknott': 'SE',
    'Addis': 'ET', 'Daniel Belanger': 'CA', 'KMFDM': 'DE',
    'Portishead': 'GB', 'Cowboy Junkie': 'CA', 'Lisa Gerrard': 'AU',
    'Victor Wooten': 'US', 'Elizabeth Cotten': 'US', 'The Winstons': 'US',
    'Liana La Havas': 'GB', 'Jazz Emu': 'GB', 'Ellie Dixon': 'GB',
    'Jake Wesley Rogers': 'US', 'La Roux': 'GB', 'Moses Sumney': 'US',
    'Weyes Blood': 'US', 'Charles Aznavour': 'FR', 'Sam Ryder': 'GB',
    'half alive': 'US', 'modernlove': 'IE', 'ripe': 'US', 'flor': 'US',
    'The O\u2019Reillys And The Paddyhats': 'DE', 'Dexys Midnight Runners': 'GB',
    'Kid Laroi': 'AU', 'Kenshi Yonezu, Hikaru Utada': 'JP',
    'BTOB (\ube44\ud22c\ube44': 'KR', 'IU(\uc544\uc774\uc720': 'KR',
    '\uc2e0\uc6a9\uc7ac (Shin Yong Jae': 'KR',
    # K-pop groups
    'Stray Kids': 'KR', 'ATEEZ': 'KR', 'SEVENTEEN': 'KR',
    'TWICE': 'KR', 'Red Velvet': 'KR', 'aespa': 'KR', 'IVE': 'KR',
    'NewJeans': 'KR', 'ITZY': 'KR', 'LOONA': 'KR', 'BTS': 'KR',
    'BLACKPINK': 'KR', 'EXO': 'KR', 'GOT7': 'KR', 'MONSTA X': 'KR',
    'SHINee': 'KR', 'Big Bang': 'KR', 'Mamamoo': 'KR',
    'Dreamcatcher': 'KR', 'EVERGLOW': 'KR',
    # Western pop
    'Shawn Mendes': 'CA', 'Camila Cabello': 'CU', 'One Direction': 'GB',
    'Harry Styles': 'GB', 'ZAYN': 'GB', 'Little Mix': 'GB',
    'Clean Bandit': 'GB', 'Rudimental': 'GB', 'Disclosure': 'GB',
    'Zedd': 'DE', 'Marshmello': 'US', 'The Chainsmokers': 'US',
    'Kygo': 'NO', 'Martin Garrix': 'NL', 'Ti\u00ebsto': 'NL',
    'Deadmau5': 'CA', 'Skrillex': 'US', 'David Guetta': 'FR',
    'DJ Snake': 'FR', 'Flume': 'AU', 'ODESZA': 'US',
    'Bonobo': 'GB', 'Four Tet': 'GB', 'Caribou': 'CA',
    'Aphex Twin': 'GB', 'Flying Lotus': 'US', 'Thundercat': 'US',
    'Kaytranada': 'CA', 'The Weeknd': 'CA', 'Drake': 'CA',
    'SZA': 'US', 'Frank Ocean': 'US', 'Daniel Caesar': 'CA',
    'Conan Gray': 'US', 'Olivia Rodrigo': 'US', 'Maggie Rogers': 'US',
    'Clairo': 'US', 'Mac DeMarco': 'CA', 'Joji': 'JP',
    'Rich Brian': 'ID', 'NIKI': 'ID', 'Still Woozy': 'US',
    'Benee': 'NZ', 'Boy Pablo': 'NO', 'Girl in Red': 'NO',
    'beabadoobee': 'GB', 'Cavetown': 'GB', 'Rex Orange County': 'GB',
    'Jon Bellion': 'US', 'DNCE': 'US', 'Hailee Steinfeld': 'US',
    '5 Seconds of Summer': 'AU', 'Niall Horan': 'IE',
    'Louis Tomlinson': 'GB', 'The Vamps': 'GB',
    'Major Lazer': 'US', 'Steve Aoki': 'US', 'Nicki Minaj': 'TT',
    'Doja Cat': 'US', 'Lil Nas X': 'US', 'Jack Harlow': 'US',
    'Megan Thee Stallion': 'US', 'Cardi B': 'US',
    'GloRilla': 'US', 'Ice Spice': 'US', 'Coi Leray': 'US',
    'Summer Walker': 'US', 'H.E.R.': 'US', 'Jhen\u00e9 Aiko': 'US',
    'Kehlani': 'US', 'Tinashe': 'US', 'Normani': 'US',
    'Rina Sawayama': 'JP', 'Yungblud': 'GB', 'Machine Gun Kelly': 'US',
    'Willow': 'US', 'Oliver Tree': 'US', 'Tai Verdes': 'US',
    'Surf Mesa': 'US', 'Powfu': 'CA', '24kGoldn': 'US',
    'Iann Dior': 'PR', 'The Kid Laroi': 'AU',
}

seeded = 0
for artist, country in final_seed.items():
    key = artist.strip()
    if key and (key not in cache or not cache[key]):
        cache[key] = country
        seeded += 1

# Mark obvious song titles as empty
song_titles = [
    'Faded', 'Stay', 'Silhouette', 'Any Other Way', 'Afterglow', 'Rivers',
    'Broken', 'Wings', 'One', 'Radio', 'Sad', 'War', 'Rare', 'Yummy',
    'DNA', 'Rain', 'Peaches', 'Frozen', 'Break', 'Run Away', 'Sen',
    'Love', 'Wet', 'Talk', '2021', '2012', '2013', '2014', 'TGIF', 'LOSER',
    'from The Myth', '4/16/18', 'Give it up', 'I Am Changing', 'My World',
    'Pitfalls', 'Missing Piece', 'For River', 'More than Friends',
    'Unnamed Song', 'Brightest Light', 'Bye Bye Bye', 'Pierce the Night',
    'Hero', 'stone cold', 'Battle Against A True Hero', 'Pegate',
    'Falling Apart', 'I can\u2019t Decide', 'The Violin Song', 'Sanctify',
    'Love Is A Game', 'La Macarena', 'Wings Clipped', 'SORRY, SORRY',
    'Christmas c\u2019mon', 'Hole In My Heart', 'Hunter of Stars',
    'Theory of Everything', 'At the Speed of Light', 'See You Soon',
    'No title', 'I\u2019m Glad You\u2019re Evil Too', 'Ambiguous',
    'Blood//Water', 'Fall in the Dark', 'Nero Bali', 'Va va vis',
    'The Hound And The Fox', 'Demons Are A Girl\u2019s Best Friend',
    'Time in a bottle', 'Toi Et Moi', 'No Help', 'O.D.D.',
    'Greatest Showman', 'LacrimA', 'I Can Fly', 'I Saw Red',
    'Luce che entra', 'Drenched', 'Fly Freely', 'Atlantico',
    'Siren Song', 'Sweet Child O\u2019 Mine', 'Seven Nation Army',
    'Isic Tutor', 'That\u2019s Why I Gave Up on Music', 'You Raise Me Up',
    'I\u2019m Stuck', 'Station Waggin', 'Forever Love',
    'Meet Me On The Battlefield', 'Downtown Shutdown', 'Looking At The Moon',
    'good together', 'Darling It\u2019s You', 'Until My Voice Is Gone',
    'Please Don\u2019t Go', 'Tongue', 'hello shadow', 'affection',
    'letting go', 'guitarmass', 'running', 'play with fire',
    'brightest light', 'I know places', 'first time', 'a Sample song',
    'Light a Fire', 'Apple Tree', 'Flashlight', 'I love you too much',
    'Nothing Is As It Seems', 'Something Good', 'A Little Messed Up',
    '6 Underground', 'Changa', 'Manual of Youth', 'Our Planet',
    'Love Goes On and On', 'Something Just Like This', 'You Know My Name',
    'I Need Love', 'The Pan Within', 'Tribute', 'Watching You Walk Away',
    'Heavyweight', 'One Look', 'Anything But This', 'The Love',
    'Caffeine', 'Where Am I At', 'Nobody Here', 'Rich Love',
    'caramelldansen', 'Glad It\u2019s You', 'One Forgotten Night',
    'Speed of Light', 'Hate You', 'Wish You Well', 'Can You Feel the Sun',
    'So Called Love', 'Resurrections', 'Show Me What You Got',
    'It\u2019s Everyday Bro', 'Temtem Up', 'Baby Shark', 'Don\u2019t Wait Up',
    'Lonely Christmas', 'Believe Me', 'Sad in the Summer', 'LA DI DA',
    'Never Gonna Give You Up', 'Hentai', 'Aphrodite', 'RIOT!',
    'Bet On It', 'Living in the Shadows', 'Lieblingsmensch', 'Lifesaver',
    'Impossible Bass Solo', 'Contagious', 'Easy Breezy', 'Expectation',
    'Press Start', 'Patience', 'Through Money', 'Love Yourself',
    'Go the Distance', 'Baka Mitai', 'Thong Song', 'The Christmas Shoes',
    'Move Mountains', 'S.L.U.T.', 'My High', 'Zombie Song',
    'Mad About You', 'God Only Knows', 'Beauty', 'Dive Back in Time',
    'Red Dress', 'Once More', 'Like That', 'Conformista', 'Deja Vu',
    'The Last Bullet', 'Mind Your Manners', 'Guitar Sound', 'No Good',
    'He\u2019s a Pirate', 'Give Me Five', 'Stranger', 'Surface Pressure',
    'Hullabaloo', 'Hey There Delilah', 'Wish You Were the Whiskey',
    'Puck Footin', 'One Like Putin', 'Falling For You', 'Guitar Song',
    'Rolodex City', 'apple bomb', 'rock the nation', 'out of my way',
    'Havana', 'Change', 'Fallin\u2019', 'Rum Pum Pum', 'Elegi', 'Chance',
    'This Time', 'Proud', 'Angelina', 'C\u2019est la vie',
    'Movin\u2019 on Up', 'Stereo Hearts', 'A Bailar Calypso', 'Replay',
    'Ride On Time', 'Ride on Time', 'Treat Me Like a Slut',
    'I Put a Spell on You', 'Confide In Me', 'Meltdown',
    'Tonight, Tonight, Tonight', 'dumb dumb', 'run boy run',
    'Night of Bloom', 'Wellerman', 'Naive Nocturne', 'Take Me Maybe',
    'EEEAAAOOO', 'Irish Way', 'Lambada (1989', 'Enough',
    'It Is What It Is', 'Song of the Night', 'I\u2019m Feeling Fine',
    'Abyssal Zone', 'The Grudge', 'Weightless', 'A Good Song Never Dies',
    'Anybody But You', 'A Whole New World', 'Just a Man', 'First Kiss',
    'Pray For Me', 'sweet Caroline', 'Comeback Queen',
    'Walk on the Wild Side', 'misery meat', '16 Tons', 'Departure',
    'Little Lion Man', 'Fortunate son', 'Release Me', 'don\u2019t forget me',
    'Frozen', 'When You Wish Upon a Star', 'Nightglow',
    'Walking On A Dream', 'Danger Zone', 'Fire on the Mountain',
    'Peaches', 'Skate Blade', 'Can You Feel My Heart', '90000 words',
    'Comptine d\u2019un autre ete', 'Let\u2019s Stay Together',
    'Careless Whisper', 'In Your Eyes', 'Fight the Power',
    'Sittin\u2019 On) The Dock of the Bay', 'Party Rock Anthem',
    'Raise Hell', 'bad guy', 'Lonely in Tokyo', 'Hotline Bling',
    'Toxic', 'Heartbreak Hotel', 'Havana', 'Crazy in Love',
    'Never Gonna Give You Up', 'Like a Rolling Stone',
    'No Tears left to Cry', 'My generation', 'Always remember us this way',
    'paperback writer', 'Summer of \u201969', 'play that funky music',
    'unchained melody', 'I Got You (I Feel Good',
    'Obstacle 1', 'You Are My starship',
    'Cheeseburger In Paradise', 'Walking On A Dream',
    'Sweet Child O\u2019 Mine', 'I\u2019m the alpha (we own the night',
]

for title in song_titles:
    if title not in cache:
        cache[title] = ''
        seeded += 1

with open(CACHE_PATH, 'w', encoding='utf-8') as f:
    json.dump(cache, f, ensure_ascii=False, indent=2)

print(f'Seeded + marked {seeded} entries. Cache: {len(cache)} total')
