#!/usr/bin/env python3
"""Batch 5: Seed remaining real artists with country codes."""

import json
import os

COUNTRY_MAP = {
    # Real artists with 1 song that need mapping
    'Bachelorette': 'NZ',  # Björk song but listed as artist
    'Backtrack': 'US',
    'Bad Apple': 'JP',  # Touhou
    'Bag Raiders': 'AU',
    'Bahari': 'US',
    'Barenaked Ladies': 'CA',
    'Barenaked ladies': 'CA',
    'Barlow Girl': 'US',
    'Bastian Baker & Yves Larock': 'CH',
    'Baz Luhrmann': 'AU',
    'Beach Bunny': 'US',
    'Beijing Welcomes You': 'CN',
    'Belinda Carlisle': 'US',
    'Belot': 'FR',
    'Benny': 'SE',
    'BFA': 'US',
    'BIGMAN': 'US',
    'BLOW': 'US',
    'Break of Reality': 'US',
    'Break Of Reality': 'US',
    'Brett Domino': 'UK',
    'Brittney Spears': 'US',
    'BRADIO': 'JP',
    'BTOB (비투비)': 'KR',
    'Caravan Palace': 'FR',
    'Chase Holfelder': 'US',
    'Christina Aguilera': 'US',
    'Circuit des Yeux': 'US',
    'CircusP': 'JP',
    'Clara C': 'US',
    'Clean Bandit and Mabel': 'UK',
    'Clocks and Clouds': 'DE',
    'Cody Lovass': 'US',
    'Con Bro Chill': 'US',
    'Corpse Husband': 'US',
    'Daniel Bélanger': 'CA',
    'David Choi': 'US',
    'Dazbee': 'JP',
    'Dido': 'UK',
    'DJ Striden': 'SE',
    'DNCE': 'US',
    'Dolvondo': 'US',
    'Echosmith': 'US',
    'Edvin Marton': 'HU',
    'Edwin McCain': 'US',
    'Eliza Rickman': 'US',
    'Eve': 'JP',
    'Exo': 'KR',
    'F-777': 'US',
    'Faouzia': 'CA',
    'FDVM': 'FR',
    'Feeder': 'UK',
    'Fickle Friends': 'US',
    'Fleur East': 'UK',
    'Fonzi M': 'US',
    'Gareth Emery feat. Christina Novelli': 'GB',
    'Giovanni Allevi': 'IT',
    'Guy Sebastian': 'AU',
    'Hagali': 'US',
    'Haschak Sisters': 'US',
    'Hudson Mohawke': 'GB',
    'Hurts': 'UK',
    'I AM THEY': 'US',
    'Illenium': 'US',
    'Imy': 'JP',
    'Incantation': 'US',
    'Infected mushroom': 'IL',
    'Ingrid Michaelson': 'US',
    'Ivy Levan': 'US',
    'Jacob Sartorius': 'US',
    'Jake Manisto': 'US',
    'James Tw': 'UK',
    'Jason Derulo': 'US',
    'Jason Mraz': 'US',
    'Jay Z': 'US',
    'Jennifer Lopez': 'US',
    'Jessie Ware': 'UK',
    'Jhené Aiko': 'US',
    'Jikky Bytt': 'JP',
    'Joanna Newsom': 'US',
    'Joe Hisaishi': 'JP',
    'Joe Satriani': 'US',
    'John Cale': 'UK',
    'Johnossi': 'SE',
    'Jon Bellion': 'US',
    'Jon Cozart': 'US',
    'Jordan Gagne': 'US',
    'KANA-BOON': 'JP',
    'Kajiura Yuki': 'JP',
    'Kana Nishino': 'JP',
    'Kambido': 'US',
    'Karmin': 'US',
    'Kat DeLuna': 'US',
    'Kelly Clarkson': 'US',
    'Kelly Sweet': 'US',
    'Kevin Leonardo': 'US',
    'Khalid': 'US',
    'Kimi no nawa': 'JP',
    'Kitsune^2': 'JP',
    'Kokia': 'JP',
    'Knives At Sea': 'US',
    'Korede Bello': 'NG',
    'Krewella': 'US',
    'Kuba Oms': 'CA',
    'LACUNA COIL': 'IT',
    'Lady Antebellum': 'US',
    'Lady Gaga': 'US',
    'Lawson': 'UK',
    'Lil Uzi Vert': 'US',
    'Lil Wayne': 'US',
    'Listz': 'HU',
    'Loco Loco': 'US',
    'Lord Huron': 'US',
    'Loreen': 'SE',
    'Loren Allred': 'US',
    'Louis Cole': 'US',
    'Lxandra': 'FI',
    'Lynyrd Skynyrd': 'US',
    'M2U': 'KR',
    'Macklemore': 'US',
    'Macklemore & Ryan Lewis': 'US',
    'Madonna': 'US',
    'Mai Kuraki': 'JP',
    'Malinda': 'US',
    'Mariya Takeuchi': 'JP',
    'Martina McBride': 'US',
    'Mat Kearney': 'US',
    'Matt Burrows': 'US',
    'Mayu Maeshima': 'JP',
    'Meg Myers': 'US',
    'Melanie Martinez': 'US',
    'Michael Bublé': 'CA',
    'Michele McLaughlin': 'US',
    'Michele Mclaughin': 'US',
    'Miki Matsubara': 'JP',
    'Mike Perry': 'SE',
    'MisterWives': 'US',
    'Misterwives': 'US',
    'Monstaz': 'US',
    'Monsune': 'US',
    'Mori Calliope': 'JP',
    'Muse': 'UK',
    'My': 'US',
    'Ne-Yo': 'US',
    'Ne-yo': 'US',
    'Nerina Pallot': 'UK',
    'Nessa Barrett': 'US',
    'Niall Horan': 'IE',
    'Nick Pitera': 'US',
    'Nina Simone': 'US',
    'No Age': 'US',
    'Nurmat Sadyrov': 'KZ',
    'OBB': 'US',
    'OK Go': 'US',
    'Olly Murs': 'UK',
    'Olivia rodrigo': 'US',
    'One Republic': 'US',
    'OTR': 'US',
    'P!nk': 'US',
    'PENTATONIX': 'US',
    'Panic at the Disco': 'US',
    'Panic! at the Disco': 'US',
    'Parov Stelar': 'AT',
    'Paul McCartney': 'UK',
    'Pendulum': 'AU',
    'Perfume Genius': 'US',
    'Phil Collins': 'UK',
    'Philip Wesley': 'US',
    'Pink': 'US',
    'Pink Martini': 'US',
    'Plumb': 'US',
    'Ratt': 'US',
    'Rachel Platten': 'US',
    'Rafferty': 'UK',
    'Really Slow Motion': 'US',
    'Rebecca Black': 'US',
    'Red': 'US',
    'Rever Mieux': 'US',
    'Revivalists': 'US',
    'RiceGum': 'US',
    'RIELL': 'US',
    'Rixton': 'UK',
    'Rob thomas': 'US',
    'Runaground': 'US',
    'Ruth B.': 'CA',
    'Sabrina Claudio': 'US',
    'Sam Riegel': 'US',
    'Santana': 'US',
    'SaraSinger42': 'US',
    'Sasha Alex Sloan': 'US',
    'Sayuri': 'JP',
    'Seal': 'UK',
    'Seann Bowe': 'US',
    'Sergey Lazarev': 'RU',
    'Set It Off': 'US',
    'Set it Off': 'US',
    'Shawn Mendes, Camila Cabello': 'CA',
    'Sheppard': 'AU',
    'Simply Three': 'US',
    'Smash Into Pieces': 'SE',
    'Sly & The Family Stone': 'US',
    'Smashing Pumpkins': 'US',
    'Sody': 'UK',
    'Spice Girls': 'UK',
    'Static': 'US',
    'Static P': 'US',
    'Static-P': 'US',
    'Stellar': 'KR',
    'Steve Aoki': 'US',
    'Sting': 'UK',
    'Supertramp': 'UK',
    'Swingrowers': 'IT',
    'T.R.E.': 'UK',
    'Taio Cruz': 'UK',
    'Tatsuya': 'JP',
    'TLC': 'US',
    'Todrick Hall': 'US',
    'Tom Cochrane': 'CA',
    'Tove Lo': 'SE',
    'Train': 'US',
    'TUYU': 'JP',
    'Tuyu': 'JP',
    'Twenty One Pilots': 'US',
    'Two Steps from Hell': 'US',
    'Tyler Ward': 'US',
    'Tyler, The Creator': 'US',
    'Uncle Acid And The Deadbeats': 'GB',
    'Unlike Pluto': 'US',
    'VIXX': 'KR',
    'Valeree': 'US',
    'Valgur': 'US',
    'Vanic': 'CA',
    'Victoria Monét': 'US',
    'Victorious': 'US',
    'Vox Machina': 'US',
    'Ward Thomas': 'UK',
    'We the Kings': 'US',
    'Weathers': 'US',
    'Wham!': 'UK',
    'Wicked': 'US',
    'Wisin & Yandel': 'PR',
    'X Ambassador': 'US',
    'X Ambassadors': 'US',
    'Xi Shua Shua': 'TW',
    'Yandel': 'PR',
    'Yellow Magic Orchestra': 'JP',
    'Yohanna': 'IS',
    'Young Stoner Life': 'US',
    'Yung Zel': 'US',
    'Yurima': 'JP',
    'ZAYDE WOLF': 'US',
    'ZAYDE WØLF': 'US',
    'Zen Zen Sense': 'JP',
    'Zhou Shen': 'CN',
    'cloudfield': 'DE',
    'dodie': 'UK',
    'fujii Kaze': 'JP',
    'hiroshi sato': 'JP',
    'ill peach': 'JP',
    'lovelytheband': 'US',
    'marshmello': 'US',
    'renforshort': 'CA',
    'sleeping at last': 'US',
    'mr. chris': 'US',
    # Additional artists from unmapped list
    '96Neko': 'JP',
    '2econd 2ight 2eer': 'JP',
    'AG CLUB': 'US',
    'ANIMAL': 'US',
    'ANTEMASQUE': 'US',
    'ARAME': 'US',
    'ARCH IN YA BACK': 'US',
    'Abigail Osborn': 'US',
    'Absorption': 'US',
    'Adam Tell': 'US',
    'Adriana Figuero)': 'US',
    'Alan Lee Silva': 'US',
    'Alexa Johnson': 'US',
    'Alibi': 'US',
    'Alice Longyu Gao, Alice Glass': 'US',
    'All Levels at Once': 'US',
    'Allie X': 'CA',
    'Amadeus Electric Quartet': 'US',
    'Amar Sehmbi': 'US',
    'Amy Nuttall': 'UK',
    'Ani Lorak': 'UA',
    'Anna Blue': 'DE',
    'Anna Blue & Damien Dawn': 'DE',
    'Ansel Elgort': 'US',
    'Ariana Grande & Justin Bieber': 'US',
    'Au5': 'US',
    "Auli'i Cravalho": 'US',
    'Autoheart': 'UK',
    'Baby Keem': 'US',
    'Ben Kidson': 'AU',
    'Boy Epic': 'US',
    'BoyWithUke': 'US',
    'Breath and Bone': 'US',
    'Brian Crain': 'US',
    'Brictom': 'US',
    'Brunuhville': 'BR',
    'CVX': 'US',
    'Calema': 'FR',
    'Chain smokers': 'US',
    'Charlie Puth': 'US',
    'Charlotte Lawrence': 'US',
    'Chipettes': 'US',
    'Chris Isaak': 'US',
    'Christina Grimmie': 'US',
    'Ciara': 'US',
    'Daniel Ingram': 'CA',
    'Daniel Powter': 'CA',
    'Daya': 'US',
    'Dear Happy': 'US',
    'DEELYLE': 'US',
    'DJ Khaled': 'US',
    'Ed Sheeran': 'UK',
    'Eir Aoi': 'JP',
    'Elvis Presley': 'US',
    'Emmelie De Forest': 'DK',
    'Erykah Badu': 'US',
    'FINNEAS': 'US',
    'Fleurie': 'US',
    'Fort Minor': 'US',
    'Foster The People': 'US',
    'Fun': 'US',
    'G-easy': 'US',
    'Good Boy daisy': 'KR',
    'Gorillaz': 'UK',
    'Gwen Stefani': 'US',
    'George Harrison': 'UK',
    'Hololive': 'JP',
    'Ikimonogakari': 'JP',
    'J-An Project': 'JP',
    'Johnathan Young': 'US',
    'Juice WRLD': 'US',
    'Juice Wrld': 'US',
    'Landon Austin': 'US',
    'Liu Huan': 'CN',
    'MEGHAN TRAINOR': 'US',
    'MKTO': 'US',
    'Måns Zelmerlöw': 'SE',
    'Orange caramel': 'KR',
    'The Neighbourhood': 'US',
    'The Diamonds': 'CA',
    'Ava Max': 'US',
    'BEAST IN BLACK': 'FI',
    'Before You Exit': 'US',
    'Beth Crowley': 'US',
    'Billy Joel': 'US',
    'Black Violin': 'US',
    'Bruce Springsteen': 'US',
    'Carole and Tuesday': 'JP',
    'Christina Perri ft. Jason Mraz': 'US',
    'David Bélanger': 'CA',
    'Ellie Goulding': 'UK',
    'End of Silence': 'US',
    'Krewella': 'US',
    'Lena': 'DE',
    'Piano Guys': 'US',
    'The Cello Song': 'US',
    'Armin van Buuren feat. Sharon den Adel': 'NL',
    '96Neko': 'JP',
    'Kitsune^2': 'JP',
    'Project 46': 'CA',
    'Korede Bello': 'NG',
    'Anadolu': 'TR',
    'Francesca Maria': 'US',
    'Revolution Harmony': 'US',
}

CACHE_PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'artist_country_cache.json')

def main():
    cache = json.load(open(CACHE_PATH, 'r', encoding='utf-8'))
    added = 0
    for artist, code in COUNTRY_MAP.items():
        if artist not in cache or not cache[artist]:
            cache[artist] = code
            added += 1

    with open(CACHE_PATH, 'w', encoding='utf-8') as f:
        json.dump(cache, f, indent=2, ensure_ascii=False)

    mapped = sum(1 for v in cache.values() if v)
    print(f"Added {added} new mappings")
    print(f"Total cached: {len(cache)}")
    print(f"With country: {mapped}")

if __name__ == '__main__':
    main()
