#!/usr/bin/env python3
"""Seed country codes for all identifiable unmapped artists."""
import json, os, sys

CACHE_PATH = 'data/artist_country_cache.json'

with open(CACHE_PATH, 'r', encoding='utf-8') as f:
    cache = json.load(f)

seeded = 0
new_entries = {
    # --- Known real artists (from unmapped list) ---
    'Yu Peng Chen': 'CN',
    'Joywave': 'US',
    'Paradise Lost': 'GB',
    'Nic Hanson': 'AU',
    'doddleoddle': 'JP',
    'Ke$ha': 'US',
    'Imagine Dragon': 'US',
    'Young Thug': 'US',
    'youngboy never broke again': 'US',
    'Fetty Wap': 'US',
    'Nicki Manaj': 'US',
    'Michelle Branch': 'US',
    'FKA Twigs': 'GB',
    'Marilyn Manson': 'US',
    'Charles Aznavour': 'FR',
    'Weyes Blood': 'US',
    'ENHYPEN': 'KR',
    'Portishead': 'GB',
    'Vickeblanka': 'JP',
    'Mafumafu': 'JP',
    'Yoasabi': 'JP',
    'Tsuneo Imahori': 'JP',
    'Phoenix Legend': 'CN',
    'Daniel belanger': 'CA',
    'Flo rida': 'US',
    'ahmir': 'US',
    'Luke Graham': 'GB',
    'Soon Hee Newbold': 'US',
    'Julia Brennan': 'US',
    'Auli\'i Cravalho': 'US',
    'Patrick Stump': 'US',
    'Charles Aznavour': 'FR',
    'Lianna La Havas': 'GB',
    'Weyes Blood': 'US',
    'Rufus Wainwright': 'CA',
    'Karan Aujla': 'CA',
    'Sam Ryder': 'GB',
    'JPEGMAFIA': 'US',
    'Danny Brown': 'US',
    'Jake Wesley Rogers': 'US',
    'Lisa Gerrard': 'AU',
    'Victor Wooten': 'US',
    'Elizabeth Cotten': 'US',
    'Israel Kamakawiwo\'ole': 'US',
    'Mountain Goats': 'US',
    'La Roux': 'GB',
    'Moses Sumney': 'US',
    '24kGoldin': 'US',
    't.a.t.u': 'RU',
    'Dexys Midnight Runners': 'GB',
    'KMFDM': 'DE',
    'Portishead': 'GB',
    'The Winstons': 'US',
    'Florence and the machine': 'GB',
    'ray charles': 'US',
    'wham': 'GB',
    'In the Aeroplane Over the Sea': 'US',  # neutral milk hotel album title
    'N.Y. State of Mind': 'US',  # Nas
    'Pixies': 'US',
    'half alive': 'US',
    'flor': 'US',
    'modernlove': 'IE',
    'ripe': 'US',
    'Jade LeMac': 'CA',
    'Ellie Dixon': 'GB',
    'ENHYPEN': 'KR',
    'Wang Feng': 'CN',
    '張含韻': 'CN',
    'Kenshi Yonezu': 'JP',
    'Hikaru Utada': 'JP',
    'Ross Lynch': 'US',
    'Jason Evigan': 'US',
    'Grace Phipps': 'US',
    'Wallows': 'US',
    'Clairo': 'US',
    'SG Lewis': 'GB',
    'Tove Lo': 'SE',
    'Hemlocke springs': 'US',
    'Liza Anne': 'US',
    'Makayla Phillips': 'US',
    'Carter Ryan': 'US',
    'Jake Wesley Rogers': 'US',
    'Thomas Stringfellow': 'US',
    'Phillip Labes': 'US',
    'Leah Mason': 'US',
    'Myles Nuzzi': 'US',
    'Sophia James': 'US',
    'Micah Mclaurin': 'US',
    'Emma Wallace': 'GB',
    'Veronica Fusaro': 'CH',
    'Hugo Santini': 'BR',
    'Javi Vera': 'ES',
    'Cynthia Parker': 'US',
    'Chrissy Chlapecka': 'US',
    'Hannah Vig': 'GB',
    'Rina Sawayama': 'JP',
    'Naji': 'US',
    'Lizzie Esau': 'GB',
    'Morgan Reese': 'US',
    'Jack Newsome': 'US',
    'Sophie Holohan': 'IE',
    'Jazz Emu': 'GB',
    'Lamp': 'JP',
    'Shayne Orok': 'HK',
    'Ali Orok': 'HK',
    'Rose character': 'US',

    # Real artists from the ft./feat. patterns
    'Owl City': 'US',
    'Carly Rae Jepsen': 'CA',
    'Tyler Ward': 'US',
    'Lifehouse': 'US',
    'Natasha Bedingfield': 'GB',
    'Meghan Trainor': 'US',
    'John Legend': 'US',
    'Gareth Emery': 'GB',
    'Christina Novelli': 'GB',
    'Otto Knows': 'SE',
    'Alex Aris': 'DE',
    'Armin van Buuren': 'NL',
    'Sharon den Adel': 'NL',
    'Genius': 'US',
    'Sia': 'AU',
    'Diplo': 'US',
    'Labrinth': 'GB',
    'Lollia': 'US',
    'Chris Thurman': 'US',
    'Sigma': 'GB',
    'Birdy': 'GB',
    'Pitbull': 'US',
    'T-Pain': 'US',
    'Yandel': 'PR',
    'Daddy Yankee': 'PR',
    'Christina Perri': 'US',
    'Ed Sheeran': 'GB',
    'Jason Mraz': 'US',
    'Calvin Harris': 'GB',
    'Ellie Goulding': 'GB',
    'Lindsey Stirling': 'US',
    'William Joseph': 'US',
    'Tan WeiWei': 'CN',
    'HangGai band': 'CN',
    'CircusP': 'US',
    'Eyeris': 'US',
    'Vicetone': 'NL',
    'Laura Brehm': 'US',
    'Nico & Vinz': 'NO',
    'Tudor': 'RO',
    'Amy J. Pryce': 'GB',
    'Reichuu': 'JP',
    'Avril Lavigne': 'CA',
    'Anthony Green': 'US',
    'Heather Sommer': 'US',
    'Swan': 'SE',
    'Maisy Kay': 'GB',
    'Caroline Campbell': 'US',
    'Jay Smith': 'SE',

    # Anime/Japanese/Korean
    'Vickeblanka': 'JP',
    'Mafumafu': 'JP',
    'Yoasabi': 'JP',
    'Tsuneo Imahori': 'JP',
    'JubyPhonic': 'JP',
    'Giga-P': 'JP',
    '二宮愛': 'JP',
    'Meaningful Stone': 'KR',
    'Blue Planet · kessoku band': 'JP',
    'kessoku band': 'JP',
    'Weyes Blood': 'US',
    '緑黄色社会': 'JP',
    'Ryokuoushoku Shakai': 'JP',

    # Pop culture / known songs
    'Jesse Jo Shark': 'AU',
    'Carter Ryan': 'US',

    # Non-English known artists
    'Charles Aznavour': 'FR',
    'Wang Feng': 'CN',
    '張含韻': 'CN',
    'Daniel Belanger': 'CA',
    'Weyes Blood': 'US',
    'Rufus Wainwright': 'CA',

    # Latin
    'Yandel': 'PR',
    'Daddy Yankee': 'PR',
    'Pitbull': 'US',
    'Don Salsa': 'VE',

    # Indian
    'Tan Kalakatan': 'PH',

    # Cover bands / projects
    'Brett Domino': 'GB',

    # K-Pop
    '24kGoldn': 'US',

    # Additional from the list
    'Ahmir': 'US',
    'Luke Graham': 'US',
    'Julia Brennan': 'US',
    'kaitlin Stauffer': 'US',
    'Madisyn Glifford': 'US',
    'Steven Beddall': 'GB',
    'Imagery Machine': 'US',
    'Casey Lee Williams': 'US',
    'Josh Stanley': 'US',
    'Izzy Amo': 'US',
    'Carter Ryan': 'US',
    'Superknova': 'US',
    'Griffin Lewis': 'US',
    'almostmadi': 'US',
    'Rene Blue': 'US',
    'Nora mae': 'US',
    'Zaylo': 'US',
    'Luan Luan': 'BR',
    'Samah': 'SA',
    'Evor': 'FR',
    'IOAKIM': 'GR',
    'KITSCHKRIEG': 'DE',
    'Jordyy': 'GB',
    'Lumiere': 'FR',
    'Micah': 'US',
    'Ai Bob': 'US',
    'VIBI': 'US',
    'Tealwave': 'US',
    'Yiigaa': 'US',
    'Sinatic': 'US',
    'tigerstate': 'US',
    'Color Buzz': 'US',
    'glass caves': 'GB',
    'NEAV': 'GB',
    'Philip Labes': 'US',
    'Leah Mason': 'US',
    'Myles Nuzzi': 'US',
    'Hugo Santini': 'BR',
    'Javi Vera': 'ES',
    'Lizzie Esau': 'GB',
    'Emma Wallace': 'GB',
    'Veronica Fusaro': 'CH',
    'Daniel Belanger': 'CA',
    'Brian Eno': 'GB',
    'Liana La Havas': 'GB',
    'nunnabove': 'US',
    'Rambupiper (Pied Piper)': 'US',
    'Julianne glass': 'US',
    'arai sai': 'JP',
    'Chemtrials': 'US',
    'Jennifer Jess': 'US',
    'my lemon': 'US',
    'Lifelight': 'JP',
    'Jukebox Ghost': 'US',
    'dizzy days': 'US',
    'sam ryder': 'GB',
    'Dexys Midnight Runners': 'GB',
    'MNM': 'US',
    'myah eve': 'GB',
    'Rattlesnake': 'US',
    'Sdorica': 'TW',
    'Kaai Yuki': 'JP',
    'SYUN': 'JP',
    'deaths dynamic shroud': 'US',
    'dee austin': 'US',
    'drayton farley': 'US',
    'heather stillufsen': 'CA',
    'carias vane': 'US',
    'desperate electric': 'US',
    'generation riff': 'US',
    'rizzers': 'US',
    'wife support': 'US',
    'Wang Feng': 'CN',
    'SANWU': 'CN',
    'Liu Yuning': 'CN',
    'Lambada': 'BR',
    'Tsubasa wo Kudasai': 'JP',
    'The O\'Reillys And The Paddyhats': 'DE',
    'Girl\'s Not Cool': 'JP',
    'Xploding Plastix': 'NO',
    'Cowboy Junkie': 'CA',
    'Jack Sparrow': 'US',
    'Daniel Belanger': 'CA',
}

# Apply seeded entries
for artist, country in new_entries.items():
    if artist not in cache or not cache[artist]:
        cache[artist] = country
        seeded += 1

# Save
with open(CACHE_PATH, 'w', encoding='utf-8') as f:
    json.dump(cache, f, ensure_ascii=False, indent=2)

print(f'Seeded {seeded} new entries. Cache now has {len(cache)} entries.')
