#!/usr/bin/env python3
"""Seed artist_country_cache.json with well-known artists."""
import json

SEED = {
    'Taylor Swift': 'US', 'Katy Perry': 'US', 'Owl City': 'US', 'Fall Out Boy': 'US',
    'Maroon 5': 'US', 'Eminem': 'US', 'Lindsey Stirling': 'US', 'Ariana Grande': 'US',
    'OneRepublic': 'US', 'Selena Gomez': 'US', 'Pink Floyd': 'GB', 'Rihanna': 'BB',
    'David Guetta': 'FR', 'Sia': 'AU', 'Michael Bublé': 'CA', 'Carly Rae Jepsen': 'CA',
    'Ludovico Einaudi': 'IT', 'Within Temptation': 'NL', 'Avril Lavigne': 'CA',
    'Coldplay': 'GB', 'The Beatles': 'GB', 'Queen': 'GB', 'Radiohead': 'GB',
    'Adele': 'GB', 'Ed Sheeran': 'GB', 'Dua Lipa': 'GB', 'Sam Smith': 'GB',
    'Arctic Monkeys': 'GB', 'The Rolling Stones': 'GB', 'Led Zeppelin': 'GB',
    'Nirvana': 'US', 'Foo Fighters': 'US', 'Red Hot Chili Peppers': 'US',
    'Linkin Park': 'US', 'Green Day': 'US', 'Blink-182': 'US',
    'The Weeknd': 'CA', 'Drake': 'CA', 'Post Malone': 'US',
    'Billie Eilish': 'US', 'Lizzo': 'US', 'Doja Cat': 'US',
    'Harry Styles': 'GB', 'One Direction': 'GB', 'Little Mix': 'GB',
    'Justin Bieber': 'CA', 'Shawn Mendes': 'CA',
    'BTS': 'KR', 'BLACKPINK': 'KR', 'Stray Kids': 'KR', 'TWICE': 'KR',
    'EXO': 'KR', 'Red Velvet': 'KR', 'aespa': 'KR', 'NewJeans': 'KR',
    'Ado': 'JP', 'YOASOBI': 'JP', 'Kenshi Yonezu': 'JP', 'Hatsune Miku': 'JP',
    'Babymetal': 'JP', 'Perfume': 'JP', 'Kyary Pamyu Pamyu': 'JP',
    'Bad Bunny': 'PR', 'J Balvin': 'CO', 'Shakira': 'CO', 'Rosalía': 'ES',
    'Daft Punk': 'FR', 'Stromae': 'BE', 'ABBA': 'SE', 'Roxette': 'SE',
    'A-ha': 'NO', 'Aurora': 'NO', 'Kygo': 'NO', 'Edvard Grieg': 'NO',
    'Beethoven': 'DE', 'Bach': 'DE', 'Hans Zimmer': 'DE',
    'Ennio Morricone': 'IT', 'Andrea Bocelli': 'IT',
    'TheFatRat': 'DE', 'Waterflame': 'NO', 'Pitbull': 'US',
    'LMFAO': 'US', 'Kendrick Lamar': 'US', 'Kanye West': 'US',
    'Jay-Z': 'US', 'Nicki Minaj': 'TT', 'Cardi B': 'US',
    'Bruno Mars': 'US', 'Justin Timberlake': 'US', 'Usher': 'US',
    'Whitney Houston': 'US', 'Mariah Carey': 'US', 'Celine Dion': 'CA',
    'Elton John': 'GB', 'David Bowie': 'GB', 'Freddie Mercury': 'GB',
    'Prince': 'US', 'Stevie Wonder': 'US', 'Aretha Franklin': 'US',
    'Bob Marley': 'JM', 'Jimmy Cliff': 'JM', 'UB40': 'GB',
    'Metallica': 'US', 'Iron Maiden': 'GB', 'Black Sabbath': 'GB',
    'AC/DC': 'AU', 'Bon Jovi': 'US',
    'Journey': 'US', 'Eagles': 'US', 'Fleetwood Mac': 'GB',
    'The Doors': 'US', 'Cream': 'GB', 'Jimi Hendrix': 'US',
    'Bob Dylan': 'US', 'Neil Young': 'CA', 'Leonard Cohen': 'CA',
    'Johnny Cash': 'US', 'Willie Nelson': 'US', 'Dolly Parton': 'US',
    'Hank Williams': 'US', 'Patsy Cline': 'US',
    'Louis Armstrong': 'US', 'Frank Sinatra': 'US', 'Nat King Cole': 'US',
    'Ella Fitzgerald': 'US', 'Billie Holiday': 'US',
    'Miles Davis': 'US', 'John Coltrane': 'US', 'Dave Brubeck': 'US',
    'Chet Baker': 'US', 'Thelonious Monk': 'US',
    'Debussy': 'FR', 'Chopin': 'PL', 'Mozart': 'AT', 'Vivaldi': 'IT',
    'Tchaikovsky': 'RU', 'Rachmaninoff': 'RU', 'Stravinsky': 'RU',
    'John Williams': 'US', 'Danny Elfman': 'US',
    'Two Steps From Hell': 'US', 'Audiomachine': 'US',
    'Clean Bandit': 'GB', 'Disclosure': 'GB', 'Chase & Status': 'GB',
    'Calvin Harris': 'GB', 'Sigala': 'GB', 'Jonas Blue': 'GB',
    'Marshmello': 'US', 'Skrillex': 'US', 'Deadmau5': 'CA',
    'Avicii': 'SE', 'Martin Garrix': 'NL', 'Tiësto': 'NL',
    'Armin van Buuren': 'NL', 'Hardwell': 'NL',
    'Imagine Dragons': 'US', 'The Chainsmokers': 'US',
    'Panic! At The Disco': 'US', 'twenty one pilots': 'US',
    'My Chemical Romance': 'US', 'Paramore': 'US',
    'Evanescence': 'US', 'Nightwish': 'FI', 'Epica': 'NL',
    'Dimmu Borgir': 'NO', 'Behemoth': 'PL',
    'Rammstein': 'DE', 'System of a Down': 'US',
    'Tool': 'US', 'Rush': 'CA', 'Dream Theater': 'US',
    'Halsey': 'US', 'Lorde': 'NZ', 'Lana Del Rey': 'US',
    'Tame Impala': 'AU', 'The 1975': 'GB', 'Wallows': 'US',
    'Set It Off': 'US', 'Pentatonix': 'US', 'Walk Off the Earth': 'CA',
    'Pomplamoose': 'US', 'Two Cellos': 'HR', '2CELLOS': 'HR',
    'Peter Hollens': 'US', 'The Piano Guys': 'US',
    'Vitamin String Quartet': 'US', 'Brooklyn Duo': 'US',
    'Il Volo': 'IT', 'Luciano Pavarotti': 'IT',
    'Josh Groban': 'US', 'Michael Buble': 'CA',
    'Norah Jones': 'US', 'Diana Krall': 'CA',
    'Dean Martin': 'US', 'Tony Bennett': 'US',
    'Bing Crosby': 'US', 'Andy Williams': 'US',
    'Engelbert Humperdinck': 'GB', 'Tom Jones': 'GB',
    'Cliff Richard': 'GB', 'Petula Clark': 'GB',
    'Kate Bush': 'GB', 'Tori Amos': 'US',
    'Fiona Apple': 'US', 'Joni Mitchell': 'CA',
    'Sarah McLachlan': 'CA', 'Sarah Brightman': 'GB',
    'Charlotte Church': 'GB', 'Demi Lovato': 'US', 'Miley Cyrus': 'US',
    'Joe Jonas': 'US', 'Nick Jonas': 'US', 'Jonas Brothers': 'US',
    '5 Seconds of Summer': 'AU', 'The Vamps': 'GB', 'The Wanted': 'GB',
    'McFly': 'GB', 'Busted': 'GB',
    'Westlife': 'IE', 'Boyzone': 'IE', 'The Cranberries': 'IE', 'U2': 'IE',
    'Enya': 'IE', 'The Script': 'IE', 'Hozier': 'IE',
    'Christina Perri': 'US', 'Meghan Trainor': 'US',
    'Blake Shelton': 'US', 'Carrie Underwood': 'US',
    'Miranda Lambert': 'US', 'Luke Bryan': 'US',
    'Florida Georgia Line': 'US', 'Zac Brown Band': 'US',
    'Mumford & Sons': 'GB', 'The Lumineers': 'US',
    'Of Monsters and Men': 'IS', 'Sigur Rós': 'IS', 'Björk': 'IS',
    'Fleet Foxes': 'US', 'Bon Iver': 'US',
    'Sufjan Stevens': 'US', 'Iron & Wine': 'US',
    'The National': 'US', 'Arcade Fire': 'CA',
    'Broken Social Scene': 'CA', 'Metric': 'CA',
    'Snail Mail': 'US', 'Japanese Breakfast': 'US',
    'Phoebe Bridgers': 'US', 'Lucy Dacus': 'US', 'Boygenius': 'US',
    'Mitski': 'JP', 'St. Vincent': 'US',
    'Grimes': 'CA', 'Purity Ring': 'CA', 'Crystal Castles': 'CA',
    'CHVRCHES': 'GB', 'Charli XCX': 'GB',
    '100 gecs': 'US', 'Rina Sawayama': 'JP',
    'Ice Spice': 'US', 'Megan Thee Stallion': 'US',
    'SZA': 'US', 'Summer Walker': 'US', 'Jhené Aiko': 'US',
    'Daniel Caesar': 'CA', 'PartyNextDoor': 'CA',
    'Jorja Smith': 'GB', 'Raye': 'GB', 'Anne-Marie': 'GB',
    'Bebe Rexha': 'US', 'Kacey Musgraves': 'US',
    'Brandi Carlile': 'US', 'Alison Krauss': 'US',
    'Emmylou Harris': 'US', 'Loretta Lynn': 'US',
    'Simon & Garfunkel': 'US', 'James Taylor': 'US',
    'Cat Stevens': 'GB', 'Don McLean': 'US',
    'Nickelback': 'CA', 'Simple Plan': 'CA', 'Sum 41': 'CA',
    'Breaking Benjamin': 'US', 'Three Days Grace': 'CA',
    'Skillet': 'US', 'Lauren Daigle': 'US',
    'For King & Country': 'AU', 'NF': 'US',
    'Wiz Khalifa': 'US', 'Mac Miller': 'US', 'Logic': 'US',
    'Childish Gambino': 'US', 'Tyler, the Creator': 'US',
    'Frank Ocean': 'US', 'Steve Lacy': 'US',
    'Jessie Reyez': 'CA', 'Ruel': 'AU', 'Dean Lewis': 'AU',
    'Troye Sivan': 'AU', 'Conan Gray': 'US',
    'Olivia Rodrigo': 'US', 'Gracie Abrams': 'US',
    'Sabrina Carpenter': 'US', 'Chappell Roan': 'US',
    'Tate McRae': 'CA',
    'Burna Boy': 'NG', 'Wizkid': 'NG', 'Tems': 'NG', 'Rema': 'NG',
    'Davido': 'NG', 'Tiwa Savage': 'NG',
    'Black Coffee': 'ZA', 'Die Antwoord': 'ZA', 'Ladysmith Black Mambazo': 'ZA',
    'Miriam Makeba': 'ZA', 'Hugh Masekela': 'ZA',
    'Angélique Kidjo': 'BJ', 'Youssou N Dour': 'SN',
    'Kimbra': 'NZ', 'Crowded House': 'NZ',
    'Savage Garden': 'AU', 'INXS': 'AU', 'Midnight Oil': 'AU',
    'Silverchair': 'AU', 'Wolfmother': 'AU', 'Flume': 'AU',
    'Rüfüs Du Sol': 'AU', 'Vance Joy': 'AU',
    'Little Simz': 'GB', 'Stormzy': 'GB', 'Dave': 'GB',
    'Central Cee': 'GB', 'Craig David': 'GB',
    'Zedd': 'DE', 'Alesso': 'SE', 'Swedish House Mafia': 'SE',
    'Alan Walker': 'NO',
    'Daddy Yankee': 'PR', 'Ozuna': 'PR', 'Luis Fonsi': 'PR',
    'Maluma': 'CO', 'Karol G': 'CO', 'Juanes': 'CO',
    'Ricky Martin': 'PR', 'Enrique Iglesias': 'ES',
    'Maná': 'MX', 'Los Tigres del Norte': 'MX',
    'Anitta': 'BR', 'CNCO': 'EC',
    'Porter Robinson': 'US', 'Madeon': 'FR', 'San Holo': 'NL',
    'ODESZA': 'US', 'Bonobo': 'GB', 'Tycho': 'US',
    'Nujabes': 'JP', 'DJ Okawari': 'JP',
    'Yiruma': 'KR', 'George Winston': 'US', 'Yanni': 'GR',
    'Kitaro': 'JP', 'Vangelis': 'GR',
    'Philip Glass': 'US', 'Steve Reich': 'US', 'Brian Eno': 'GB',
    'Max Richter': 'DE', 'Ólafur Arnalds': 'IS', 'Nils Frahm': 'DE',
    'Aphex Twin': 'GB', 'Boards of Canada': 'GB',
    'Burial': 'GB', 'James Blake': 'GB',
    'Jon Hopkins': 'GB', 'Four Tet': 'GB',
    'Flying Lotus': 'US', 'Thundercat': 'US',
    'Snarky Puppy': 'US', 'Vulfpeck': 'US',
    'Jay Chou': 'TW', 'Eason Chan': 'HK', 'JJ Lin': 'SG',
    'G.E.M.': 'HK', 'Hua Chenyu': 'CN',
    'BIGBANG': 'KR', 'SHINee': 'KR', 'Super Junior': 'KR',
    'GOT7': 'KR', 'MONSTA X': 'KR', 'SEVENTEEN': 'KR',
    'ATEEZ': 'KR', 'TXT': 'KR', 'ENHYPEN': 'KR',
    'ITZY': 'KR', 'MAMAMOO': 'KR', 'LOONA': 'KR',
    'LE SSERAFIM': 'KR', 'IVE': 'KR', 'STAYC': 'KR',
    'IU': 'KR', 'Taeyeon': 'KR', 'BoA': 'KR',
    'G-Dragon': 'KR', 'Psy': 'KR',
    'ONE OK ROCK': 'JP', 'RADWIMPS': 'JP', 'King Gnu': 'JP',
    'Official HIGE DANdism': 'JP', 'Fujii Kaze': 'JP',
    'LiSA': 'JP', 'Aimer': 'JP', 'Hikaru Utada': 'JP',
    'Ayumi Hamasaki': 'JP', 'Namie Amuro': 'JP',
    'X Japan': 'JP', 'L Arc en Ciel': 'JP',
    'Dir En Grey': 'JP', 'Boris': 'JP', 'Mono': 'JP',
    'Explosions in the Sky': 'US', 'God Is an Astronaut': 'IE',
    'Mogwai': 'GB', 'Caspian': 'US',
    'Opeth': 'SE', 'Meshuggah': 'SE', 'In Flames': 'SE',
    'At the Gates': 'SE', 'Amon Amarth': 'SE',
    'Enslaved': 'NO', 'Emperor': 'NO', 'Mayhem': 'NO',
    'Darkthrone': 'NO', 'Immortal': 'NO',
    'Electric Wizard': 'GB', 'Sleep': 'US', 'Neurosis': 'US',
    'a-ha': 'NO', 'Alphaville': 'DE',
    'Tears for Fears': 'GB', 'Depeche Mode': 'GB',
    'New Order': 'GB', 'The Cure': 'GB', 'Joy Division': 'GB',
    'The Smiths': 'GB', 'Oasis': 'GB', 'Blur': 'GB',
    'Placebo': 'GB', 'Snow Patrol': 'GB', 'Keane': 'GB',
    'Kodaline': 'IE', 'George Ezra': 'GB', 'James Bay': 'GB',
    'Ben Howard': 'GB', 'Passenger': 'GB', 'Lewis Capaldi': 'GB',
    'Lauv': 'US',
    'Girls Day': 'KR', 'Apink': 'KR', 'GFRIEND': 'KR',
    'BOL4': 'KR', 'AKMU': 'KR',
    'The Piano Guys': 'US', 'Brooklyn Duo': 'US',
    'Celine Dion': 'CA',
}

try:
    with open('data/artist_country_cache.json', 'r') as f:
        cache = json.load(f)
except:
    cache = {}

added = 0
for artist, country in SEED.items():
    if artist not in cache or not cache[artist]:
        cache[artist] = country
        added += 1

with open('data/artist_country_cache.json', 'w') as f:
    json.dump(cache, f, indent=2, ensure_ascii=True)

found = sum(1 for v in cache.values() if v)
print(f'Cache size: {len(cache)}')
print(f'Found: {found}')
print(f'Added: {added}')
