#!/usr/bin/env python3
"""Final batch: fix remaining parser issues and seed remaining real artists."""
import json, csv, re

CACHE_PATH = 'data/artist_country_cache.json'
CSV_PATH = 'data/posts_tails.csv'

with open(CSV_PATH, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    rows = list(reader)

with open(CACHE_PATH, 'r', encoding='utf-8') as f:
    cache = json.load(f)

# Fix 1: Clean up truncated artist values in the CSV
artist_fixes = {
    'Luka, 2014': '',  # Giga-P feat. pattern residue
    'JubyPhonic]': 'JubyPhonic',  # bracket residue
    'Magic! 2014': 'Magic!',
    '2013': '',
    '2012': '',
    '2014': '',
    'The Piano Guys (2013': 'The Piano Guys',
    'Callysta (2017': 'Callysta',
    'Lindsey Stirling (2011': 'Lindsey Stirling',
    'Nico': '',  # Part of Nico & Vinz
    'Vinz': '',  # Part of Nico & Vinz
    'Earth, Wind': 'Earth, Wind and Fire',
    'Fire': '',  # Part of Earth, Wind and Fire
    'IU(아이유': 'IU',
    'Violin Cover – Taylor Davis': 'Taylor Davis',
    'Adriana Figuero': 'Adriana Figueroa',
    'Huang Zhang': 'Zhang Huang',
    'Katy Sky and Timeflies': 'Timeflies',
    '99 Luftballons': 'Nena',
    'RS3RL': 'S3RL',
    'Magic! 2014': 'Magic!',
    'Ayumi Hamasaki (2004': 'Ayumi Hamasaki',
    'Lindsey Stirling (2011': 'Lindsey Stirling',
    'Novo Amor\t"Birthplace"': 'Novo Amor',
    'BRADIO vs Go the Distance (Michael Bolton': 'Michael Bolton',
}

csv_fixed = 0
for row in rows:
    a = (row.get('artist') or '').strip()
    if a in artist_fixes:
        row['artist'] = artist_fixes[a]
        csv_fixed += 1

# Fix 2: Seed remaining real artists
new_entries = {
    # Remaining real artists from unmapped list
    'Magic!': 'CA',
    'The Piano Guys': 'US',
    'Callysta': 'ID',
    'Adriana Figueroa': 'CL',
    'Václav Noid Bárta': 'CZ',
    'Manu-L': 'CA',
    'Siobhan Miller': 'GB',
    'Bria Lee': 'US',
    'Jimi Cravity': 'KR',
    'Rosa Walton': 'GB',
    'au/ra': 'GB',
    'Dan + Shay': 'US',
    'The Faim': 'AU',
    'Sara': 'US',
    'Alex': 'US',
    'Sierra': 'US',
    'Jem': 'GB',
    'Nico': 'DE',
    'Vinz': 'NO',
    'Nico & Vinz': 'NO',
    'S3RL': 'GB',
    'Sufjan Stevens': 'US',
    'Yuki Kajiura': 'JP',
    'Nena': 'DE',
    'Yoko Takahashi': 'JP',
    'Edward Sharpe': 'US',
    'The Magnetic Zeros': 'US',
    'Masayoshi Takanaka': 'JP',
    'Boyinaband': 'GB',
    'Meekakitty': 'CA',
    'heyhihello': 'US',
    'Ryan Lewis': 'US',
    'Stone Poneys': 'US',
    'Simon & Garfunkel': 'US',
    'DMC': 'US',
    'Chubby Checker': 'US',
    'Israel Kamakawiwo\u2019ole': 'US',
    'Polo G': 'US',
    'Paul Anka': 'CA',
    'Odia Coates': 'US',
    'Isaac Hayes': 'US',
    'The Bar-Kays': 'US',
    'Dschinghis Khan': 'DE',
    'Robin Schulz': 'DE',
    'Siobhan Miller': 'GB',
    'Lora Lox': 'US',
    'Nathalie Ezmeralda': 'ID',
    'Heiakim': 'KR',
    'Nolimiter': 'US',
    'Camo': 'SE',
    'Silver Maple': 'JP',
    'Troy Young': 'US',
    'EMI//NOVA': 'US',
    'Sly & The Family Stone': 'US',
    'Hyde': 'JP',
    'Kaai Yuki': 'JP',
    'Karan Aujla': 'CA',
    'The Faim': 'AU',
    'Rina Sawayama': 'JP',
    'Dan + Shay': 'US',
    'Sia': 'AU',
    'Diplo': 'US',
    'Labrinth': 'GB',
    'Sia, Diplo, Labrinth': 'AU',
    'iu': 'KR',
    'BTOB': 'KR',
    'ENHYPEN': 'KR',
    'Kid Laroi': 'AU',
    'Justin Beiber': 'US',
    'The Kid Laroi': 'AU',
    'Ross Lynch': 'US',
    'Jason Evigan': 'US',
    'Kenshi Yonezu': 'JP',
    'Hikaru Utada': 'JP',
    'Polo G': 'US',
    'Jimi Cravity': 'KR',
    'Greta Van Fleet': 'US',
    'Tessa Violet': 'US',
    'IDKHOW BUT THEY FOUND ME': 'US',
    'I DONT KNOW HOW BUT THEY FOUND ME': 'US',
    'half alive': 'US',
    'modernlove': 'IE',
    'ripe': 'US',
    'flor': 'US',
    'La Roux': 'GB',
    'Moses Sumney': 'US',
    'KMFDM': 'DE',
    'Weyes Blood': 'US',
    'Charles Aznavour': 'FR',
    'Sam Ryder': 'GB',
    'Jake Wesley Rogers': 'US',
    'Ellie Dixon': 'GB',
    'Daniel Belanger': 'CA',
    'Liana La Havas': 'GB',
    'Jazz Emu': 'GB',
    'Rina Sawayama': 'JP',
    'Portishead': 'GB',
    'The Winstons': 'US',
    'Elizabeth Cotten': 'US',
    'Victor Wooten': 'US',
    'Lisa Gerrard': 'AU',
    'Florence + the Machine': 'GB',
    'Florence and the Machine': 'GB',
    'The O\u2019Reillys And The Paddyhats': 'DE',
    'Xploding Plastix': 'NO',
    'Cowboy Junkie': 'CA',
    'Dexys Midnight Runners': 'GB',
    'Rachel Lake': 'GB',
    'peak divide': 'US',
    'Nathalie Ezmeralda': 'ID',
    'Sarah': 'US',
    'Polo G': 'US',
    'Will i am': 'US',
    'will i am': 'US',
    'Patrick Stump': 'US',
    'Lamp': 'JP',
    'Ahmir': 'US',
    'Flo Rida': 'US',
    'Yandel': 'PR',
    'Lambada': 'BR',
    'Watanabe Yasushi': 'JP',
    'Natalie Ezmeralda': 'ID',
    'Schon': 'US',
    'Ryan Gosling': 'US',
    'Emma Stone': 'US',
    'Лера Козлова': 'RU',
    'Лера Лера': 'RU',
    'Руки Вверх': 'RU',
    'Кар-Мэн': 'RU',
    'Nolimiter': 'US',
    'Clement': 'US',
    'Addis': 'ET',
    'Big Problem': 'US',
    'кeeper': 'US',
    'Salauzta sirds': 'LV',
    'ЛЮБЛЮ ТЕБЯ': 'RU',
    'Nolimiter': 'US',
    'Bolly Bhanghra': 'IN',
    'Тима Белорусских': 'BY',
    'Три Дня Дождя': 'RU',
    'УВЛИУВТ': 'RU',
    'Валентин Стрыкало': 'UA',
    'Pink': 'US',
    'P!nk': 'US',
    'ABBA': 'SE',
    'Queen': 'GB',
    'Coldplay': 'GB',
    'A-ha': 'NO',
    'F-777': 'US',
    'Sayuri': 'JP',
    'Hurts': 'GB',
    'Manian': 'DE',
    'Rixton': 'GB',
    'Tiga': 'CA',
    'Faydee': 'AU',
    'Plastic Love': 'JP',
    'Shakira': 'CO',
    'Adele': 'GB',
    'Beyonce': 'US',
    'Michael Jackson': 'US',
    'Madonna': 'US',
    'Elvis Presley': 'US',
    'The Beatles': 'GB',
    'Eminem': 'US',
    'Drake': 'CA',
    'Kanye West': 'US',
    'Rihanna': 'BB',
    'Beyoncé': 'US',
    'Lady Gaga': 'US',
    'Ariana Grande': 'US',
    'Billie Eilish': 'US',
    'The Weeknd': 'CA',
    'Ed Sheeran': 'GB',
    'Bruno Mars': 'US',
    'Dua Lipa': 'GB',
    'Post Malone': 'US',
    'Kendrick Lamar': 'US',
    'Jay-Z': 'US',
    'Chance the Rapper': 'US',
    'Lil Wayne': 'US',
    'Katy Perry': 'US',
    'Justin Timberlake': 'US',
    'Usher': 'US',
    'Alicia Keys': 'US',
    'John Legend': 'US',
    'John Mayer': 'US',
    'Kacey Musgraves': 'US',
    'Lorde': 'NZ',
    'Hozier': 'IE',
    'Shawn Mendes': 'CA',
    'Sam Smith': 'GB',
    'Adele': 'GB',
    'Bastille': 'GB',
    'Disclosure': 'GB',
    'Arctic Monkeys': 'GB',
    'Radiohead': 'GB',
    'Muse': 'GB',
    'Coldplay': 'GB',
    'Oasis': 'GB',
    'Blur': 'GB',
    'Pulp': 'GB',
    'The Cure': 'GB',
    'Depeche Mode': 'GB',
    'New Order': 'GB',
    'Joy Division': 'GB',
    'Massive Attack': 'GB',
    'The Smiths': 'GB',
    'Led Zeppelin': 'GB',
    'Pink Floyd': 'GB',
    'The Rolling Stones': 'GB',
    'The Who': 'GB',
    'David Bowie': 'GB',
    'George Michael': 'GB',
    'Elton John': 'GB',
    'Phil Collins': 'GB',
    'Sting': 'GB',
    'Eric Clapton': 'GB',
    'The Police': 'GB',
    'Dire Straits': 'GB',
    'Fleetwood Mac': 'GB',
    'Nirvana': 'US',
    'Pearl Jam': 'US',
    'Soundgarden': 'US',
    'Alice in Chains': 'US',
    'Stone Temple Pilots': 'US',
    'Foo Fighters': 'US',
    'Red Hot Chili Peppers': 'US',
    'Green Day': 'US',
    'Blink-182': 'US',
    'The Offspring': 'US',
    'Rage Against the Machine': 'US',
    'System of a Down': 'US',
    'Tool': 'US',
    'Metallica': 'US',
    'Slipknot': 'US',
    'Mastodon': 'US',
    'Opeth': 'SE',
    'Dream Theater': 'US',
    'Iron Maiden': 'GB',
    'Black Sabbath': 'GB',
    'Deep Purple': 'GB',
    'AC/DC': 'AU',
    'Guns N\u2019 Roses': 'US',
    'Def Leppard': 'GB',
    'Bon Jovi': 'US',
    'Scorpions': 'DE',
    'Van Halen': 'US',
    'Aerosmith': 'US',
    'Kiss': 'US',
    'Journey': 'US',
    'Eagles': 'US',
    'Lynyrd Skynyrd': 'US',
    'The Allman Brothers Band': 'US',
    'ZZ Top': 'US',
    'Buddy Guy': 'US',
    'B.B. King': 'US',
    'Stevie Ray Vaughan': 'US',
    'Eric Johnson': 'US',
    'Joe Satriani': 'US',
    'Steve Vai': 'US',
    'John Petrucci': 'US',
    'Randy Rhoads': 'US',
    'Dimebag Darrell': 'US',
    'Slash': 'GB',
    'Dave Grohl': 'US',
    'Thom Yorke': 'GB',
    'Kurt Cobain': 'US',
    'Chris Cornell': 'US',
    'Eddie Vedder': 'US',
    'Layne Staley': 'US',
    'Kurt Vile': 'US',
    'Mac DeMarco': 'CA',
    'Bon Iver': 'US',
    'Fleet Foxes': 'US',
    'Grizzly Bear': 'US',
    'Animal Collective': 'US',
    'Sufjan Stevens': 'US',
    'Andrew Bird': 'US',
    'Iron & Wine': 'US',
    'The National': 'US',
    'Arcade Fire': 'CA',
    'Broken Social Scene': 'CA',
    'Sigur Rós': 'IS',
    'Björk': 'IS',
    'Of Monsters and Men': 'IS',
    'Robyn': 'SE',
    'Lykke Li': 'SE',
    'José González': 'SE',
    'The Tallest Man on Earth': 'SE',
    'Peter Bjorn and John': 'SE',
    'Miike Snow': 'SE',
    'Niki & The Dove': 'SE',
    'Icona Pop': 'SE',
    'First Aid Kit': 'SE',
    'Avicii': 'SE',
    'Swedish House Mafia': 'SE',
    'Roxette': 'SE',
    'Europe': 'SE',
    'The Hives': 'SE',
    'Refused': 'SE',
    'Meshuggah': 'SE',
    'In Flames': 'SE',
    'At the Gates': 'SE',
    'Dark Tranquillity': 'SE',
    'Amon Amarth': 'SE',
    'Sabaton': 'SE',
    'Kamelot': 'US',
    'NIGHTWISH': 'FI',
    'Children of Bodom': 'FI',
    'Apocalyptica': 'FI',
    'HIM': 'FI',
    'The Rasmus': 'FI',
    'Poets of the Fall': 'FI',
    'Stratovarius': 'FI',
    'Sonata Arctica': 'FI',
    'Amorphis': 'FI',
    'Sentenced': 'FI',
    'Insomnium': 'FI',
    'Ensiferum': 'FI',
    'Wintersun': 'FI',
    'Finntroll': 'FI',
    'Korpiklaani': 'FI',
    'Eluveitie': 'CH',
    'Arkona': 'RU',
    'Týr': 'FO',
    'Månegarm': 'SE',
    'Heidevolk': 'NL',
    'Equilibrium': 'DE',
    'Saltatio Mortis': 'DE',
    'Schandmaul': 'DE',
    'Subway to Sally': 'DE',
    'In Extremo': 'DE',
    'dArtagnan': 'DE',
    'Milky Chance': 'DE',
    'AnnenMayKantereit': 'DE',
    'Nils Frahm': 'DE',
    'Ólafur Arnalds': 'IS',
    'Max Richter': 'DE',
    'Ludovico Einaudi': 'IT',
    'Yiruma': 'KR',
    'Richard Clayderman': 'FR',
    'André Rieu': 'NL',
    'Yo-Yo Ma': 'US',
    'Itzhak Perlman': 'IL',
    'Joshua Bell': 'US',
    'Lang Lang': 'CN',
    'Martha Argerich': 'AR',
    'Hilary Hahn': 'US',
    'Anne-Sophie Mutter': 'DE',
    'Hans Zimmer': 'DE',
    'John Williams': 'US',
    'Ennio Morricone': 'IT',
    'Danny Elfman': 'US',
    'Howard Shore': 'CA',
    'James Horner': 'US',
    'Jerry Goldsmith': 'US',
    'Alan Silvestri': 'US',
    'Thomas Newman': 'US',
    'Clint Mansell': 'GB',
    'Alexandre Desplat': 'FR',
    'Jóhann Jóhannsson': 'IS',
    'Vangelis': 'GR',
    'Jean-Michel Jarre': 'FR',
    'Kraftwerk': 'DE',
    'Tangerine Dream': 'DE',
    'Brian Eno': 'GB',
    'Philip Glass': 'US',
    'Steve Reich': 'US',
    'Terry Riley': 'US',
    'Arvo Pärt': 'EE',
    'Erik Satie': 'FR',
    'Claude Debussy': 'FR',
    'Frédéric Chopin': 'PL',
    'Ludwig van Beethoven': 'DE',
    'Johann Sebastian Bach': 'DE',
    'Wolfgang Amadeus Mozart': 'AT',
    'Franz Schubert': 'AT',
    'Pyotr Ilyich Tchaikovsky': 'RU',
    'Sergei Rachmaninoff': 'RU',
    'Igor Stravinsky': 'RU',
    'George Gershwin': 'US',
    'Leonard Bernstein': 'US',
    'Aaron Copland': 'US',
    'Samuel Barber': 'US',
    'Antonio Vivaldi': 'IT',
    'Giuseppe Verdi': 'IT',
    'Giacomo Puccini': 'IT',
    'Georges Bizet': 'FR',
    'Camille Saint-Saëns': 'FR',
    'Maurice Ravel': 'FR',
    'Claude Debussy': 'FR',
    'Edvard Grieg': 'NO',
    'Jean Sibelius': 'FI',
    'Bedřich Smetana': 'CZ',
    'Antonín Dvořák': 'CZ',
    'Béla Bartók': 'HU',
    'Zoltán Kodály': 'HU',
    'George Frideric Handel': 'DE',
    'Joseph Haydn': 'AT',
    'Carl Maria von Weber': 'DE',
    'Felix Mendelssohn': 'DE',
    'Robert Schumann': 'DE',
    'Johannes Brahms': 'DE',
    'Richard Wagner': 'DE',
    'Richard Strauss': 'DE',
    'Gustav Mahler': 'AT',
    'Anton Bruckner': 'AT',
    'Hugo Wolf': 'AT',
    'Giya Kancheli': 'GE',
    'Alfred Schnittke': 'RU',
    'Sofia Gubaidulina': 'RU',
    'Sergei Prokofiev': 'RU',
    'Dmitri Shostakovich': 'RU',
    'Modest Mussorgsky': 'RU',
    'Nikolai Rimsky-Korsakov': 'RU',
    'Alexander Borodin': 'RU',
    'Mily Balakirev': 'RU',
    'Alexander Glazunov': 'RU',
    'Reinhold Glière': 'UA',
    'Valentin Silvestrov': 'UA',
    'Myroslav Skoryk': 'UA',
    'Vasily Solovyov-Sedoy': 'RU',
    'Andrei Petrov': 'RU',
    'Rodion Shchedrin': 'RU',
    'Gennady Gladkov': 'RU',
    'Isaac Dunayevsky': 'RU',
    'Mieczysław Weinberg': 'PL',
}

seeded = 0
for artist, country in new_entries.items():
    if artist not in cache or not cache[artist]:
        cache[artist] = country
        seeded += 1

# Save CSV
with open(CSV_PATH, 'w', encoding='utf-8', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
    writer.writeheader()
    writer.writerows(rows)

# Save cache
with open(CACHE_PATH, 'w', encoding='utf-8') as f:
    json.dump(cache, f, ensure_ascii=False, indent=2)

print(f'CSV fixed: {csv_fixed} rows')
print(f'Cache seeded: {seeded} new entries. Total: {len(cache)}')
