"""
challenge_db.py — Curated challenge database and genre alias mappings.
Standalone module-level data extracted from taste_engine.py for testability.
"""
from typing import Dict, List


# ============================================================
# Curated challenge songs — critically acclaimed/widely-loved tracks
# across diverse genres, organized by tier.
# ============================================================

CHALLENGE_DB: List[Dict] = [
    {'artist': "Queen", 'song': "Bohemian Rhapsody", 'genre': "Classic Rock", 'year': 1975, 'acclaim': "RS 500, 1B+ streams, genre-defying masterpiece", 'tier': "legendary", 'listen_score': 99},
    {'artist': "Led Zeppelin", 'song': "Stairway to Heaven", 'genre': "Classic Rock", 'year': 1971, 'acclaim': "Widely considered the greatest rock song ever", 'tier': "legendary", 'listen_score': 99},
    {'artist': "Pink Floyd", 'song': "Comfortably Numb", 'genre': "Progressive Rock", 'year': 1979, 'acclaim': "RS 500, iconic guitar solos, masterpiece", 'tier': "legendary", 'listen_score': 98},
    {'artist': "The Beatles", 'song': "A Day in the Life", 'genre': "Classic Rock", 'year': 1967, 'acclaim': "Often ranked #1 song of all time", 'tier': "legendary", 'listen_score': 99},
    {'artist': "The Rolling Stones", 'song': "Gimme Shelter", 'genre': "Classic Rock", 'year': 1969, 'acclaim': "RS 500, one of the greatest rock songs", 'tier': "legendary", 'listen_score': 98},
    {'artist': "The Who", 'song': "Baba O'Riley", 'genre': "Classic Rock", 'year': 1971, 'acclaim': "RS 500, iconic rock anthem", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Bruce Springsteen", 'song': "Born to Run", 'genre': "Classic Rock", 'year': 1975, 'acclaim': "RS 500, the ultimate rock anthem", 'tier': "legendary", 'listen_score': 98},
    {'artist': "The Doors", 'song': "Riders on the Storm", 'genre': "Classic Rock", 'year': 1971, 'acclaim': "RS 500, haunting masterpiece", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Jimi Hendrix", 'song': "All Along the Watchtower", 'genre': "Classic Rock", 'year': 1968, 'acclaim': "RS 500, greatest cover of all time", 'tier': "legendary", 'listen_score': 98},
    {'artist': "The Eagles", 'song': "Hotel California", 'genre': "Classic Rock", 'year': 1977, 'acclaim': "1B+ streams, iconic guitar solos", 'tier': "legendary", 'listen_score': 97},
    {'artist': "AC/DC", 'song': "Back in Black", 'genre': "Classic Rock", 'year': 1980, 'acclaim': "One of the best-selling songs ever", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Dire Straits", 'song': "Sultans of Swing", 'genre': "Classic Rock", 'year': 1978, 'acclaim': "RS 500, masterful guitar work", 'tier': "legendary", 'listen_score': 96},
    {'artist': "U2", 'song': "With or Without You", 'genre': "Classic Rock", 'year': 1987, 'acclaim': "RS 500, iconic anthem", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Fleetwood Mac", 'song': "Dreams", 'genre': "Classic Rock", 'year': 1977, 'acclaim': "1B+ streams, iconic production", 'tier': "classic", 'listen_score': 97},
    {'artist': "Kendrick Lamar", 'song': "Alright", 'genre': "Hip-Hop", 'year': 2015, 'acclaim': "Grammy winner, cultural anthem, 1B+ streams", 'tier': "modern_classic", 'listen_score': 98},
    {'artist': "Notorious B.I.G.", 'song': "Juicy", 'genre': "Hip-Hop", 'year': 1994, 'acclaim': "RS 500, greatest hip-hop song of all time", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Tupac", 'song': "Changes", 'genre': "Hip-Hop", 'year': 1998, 'acclaim': "Cultural anthem, iconic message", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Outkast", 'song': "Hey Ya!", 'genre': "Hip-Hop", 'year': 2003, 'acclaim': "Grammy winner, genre-blending masterpiece", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Lauryn Hill", 'song': "Doo Wop (That Thing)", 'genre': "Hip-Hop/R&B", 'year': 1998, 'acclaim': "Grammy winner, RS 500", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "Nas", 'song': "N.Y. State of Mind", 'genre': "Hip-Hop", 'year': 1994, 'acclaim': "RS 500, lyrical masterpiece", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Wu-Tang Clan", 'song': "C.R.E.A.M.", 'genre': "Hip-Hop", 'year': 1993, 'acclaim': "RS 500, iconic hip-hop track", 'tier': "legendary", 'listen_score': 97},
    {'artist': "A Tribe Called Quest", 'song': "Can I Kick It?", 'genre': "Hip-Hop", 'year': 1990, 'acclaim': "RS 500, jazz-rap masterpiece", 'tier': "legendary", 'listen_score': 95},
    {'artist': "Dr. Dre", 'song': "Still D.R.E.", 'genre': "Hip-Hop", 'year': 1999, 'acclaim': "Iconic West Coast hip-hop anthem", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Jay-Z", 'song': "99 Problems", 'genre': "Hip-Hop", 'year': 2003, 'acclaim': "Grammy winner, iconic", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Kanye West", 'song': "Runaway", 'genre': "Hip-Hop", 'year': 2010, 'acclaim': "Critically acclaimed masterpiece", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "MF DOOM", 'song': "Rapp Snitch Knishes", 'genre': "Hip-Hop", 'year': 2004, 'acclaim': "Cult classic, underground legend", 'tier': "cult", 'listen_score': 95},
    {'artist': "Missy Elliott", 'song': "Get Ur Freak On", 'genre': "Hip-Hop/R&B", 'year': 2001, 'acclaim': "Grammy winner, groundbreaking", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Daft Punk", 'song': "One More Time", 'genre': "Electronic", 'year': 2000, 'acclaim': "1B+ streams, defined a generation of dance music", 'tier': "modern_classic", 'listen_score': 98},
    {'artist': "Aphex Twin", 'song': "Windowlicker", 'genre': "Electronic/IDM", 'year': 1999, 'acclaim': "Groundbreaking electronic, RS 500", 'tier': "cult", 'listen_score': 95},
    {'artist': "Massive Attack", 'song': "Teardrop", 'genre': "Trip-Hop", 'year': 1998, 'acclaim': "Defined trip-hop, iconic", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "Boards of Canada", 'song': "Roygbiv", 'genre': "Electronic/Ambient", 'year': 1998, 'acclaim': "Influential ambient electronic masterpiece", 'tier': "cult", 'listen_score': 94},
    {'artist': "Kraftwerk", 'song': "The Model", 'genre': "Electronic", 'year': 1978, 'acclaim': "Pioneered electronic music, hugely influential", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Burial", 'song': "Archangel", 'genre': "Electronic", 'year': 2007, 'acclaim': "Defined a decade of UK electronic music", 'tier': "cult", 'listen_score': 97},
    {'artist': "Flying Lotus", 'song': "Never Catch Me", 'genre': "Electronic/Jazz", 'year': 2014, 'acclaim': "Genre-defying electronic masterpiece", 'tier': "cult", 'listen_score': 95},
    {'artist': "Jon Hopkins", 'song': "Immunity", 'genre': "Electronic", 'year': 2013, 'acclaim': "Modern electronic masterpiece", 'tier': "cult", 'listen_score': 96},
    {'artist': "Caribou", 'song': "Can't Do Without You", 'genre': "Electronic", 'year': 2014, 'acclaim': "Critically adored electronic pop", 'tier': "cult", 'listen_score': 95},
    {'artist': "Bonobo", 'song': "Kerala", 'genre': "Electronic", 'year': 2017, 'acclaim': "Modern electronic classic", 'tier': "cult", 'listen_score': 94},
    {'artist': "Four Tet", 'song': "Love Cry", 'genre': "Electronic", 'year': 2010, 'acclaim': "Influential electronic masterpiece", 'tier': "cult", 'listen_score': 95},
    {'artist': "The Chemical Brothers", 'song': "Hey Boy Hey Girl", 'genre': "Electronic/Dance", 'year': 1999, 'acclaim': "RS 500, iconic dance anthem", 'tier': "cult", 'listen_score': 96},
    {'artist': "Fatboy Slim", 'song': "Right Here, Right Now", 'genre': "Electronic/Dance", 'year': 1998, 'acclaim': "Iconic dance track, cultural touchstone", 'tier': "cult", 'listen_score': 95},
    {'artist': "Justice", 'song': "D.A.N.C.E.", 'genre': "Electronic/House", 'year': 2007, 'acclaim': "Grammy winner, modern dance classic", 'tier': "cult", 'listen_score': 96},
    {'artist': "Thom Yorke", 'song': "Hearing Damage", 'genre': "Electronic", 'year': 2009, 'acclaim': "Haunting electronic masterpiece", 'tier': "cult", 'listen_score': 95},
    {'artist': "Miles Davis", 'song': "So What", 'genre': "Jazz", 'year': 1959, 'acclaim': "Greatest jazz album of all time (Kind of Blue)", 'tier': "legendary", 'listen_score': 99},
    {'artist': "John Coltrane", 'song': "My Favorite Things", 'genre': "Jazz", 'year': 1961, 'acclaim': "Revolutionary jazz, masterpiece", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Aretha Franklin", 'song': "Respect", 'genre': "Soul", 'year': 1967, 'acclaim': "Cultural anthem, RS 500 #1", 'tier': "legendary", 'listen_score': 99},
    {'artist': "Stevie Wonder", 'song': "Superstition", 'genre': "Funk/Soul", 'year': 1972, 'acclaim': "1B+ streams, iconic funk", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Marvin Gaye", 'song': "What's Going On", 'genre': "Soul", 'year': 1971, 'acclaim': "RS 500 #1, cultural milestone", 'tier': "legendary", 'listen_score': 99},
    {'artist': "Nina Simone", 'song': "Feeling Good", 'genre': "Jazz/Soul", 'year': 1965, 'acclaim': "Iconic, 1B+ streams, timeless", 'tier': "legendary", 'listen_score': 98},
    {'artist': "James Brown", 'song': "I Got You (I Feel Good)", 'genre': "Funk", 'year': 1965, 'acclaim': "Godfather of Soul, iconic", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Ray Charles", 'song': "Georgia on My Mind", 'genre': "Soul", 'year': 1960, 'acclaim': "RS 500, timeless classic", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Etta James", 'song': "At Last", 'genre': "Soul", 'year': 1960, 'acclaim': "Timeless classic, iconic", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Charles Mingus", 'song': "Moanin'", 'genre': "Jazz", 'year': 1959, 'acclaim': "Jazz masterpiece", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Herbie Hancock", 'song': "Chameleon", 'genre': "Jazz/Funk", 'year': 1973, 'acclaim': "Jazz-funk masterpiece", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Earth, Wind and Fire", 'song': "September", 'genre': "Funk", 'year': 1978, 'acclaim': "1B+ streams, timeless funk party anthem", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Radiohead", 'song': "Paranoid Android", 'genre': "Alternative Rock", 'year': 1997, 'acclaim': "RS 500, one of the most acclaimed alt songs", 'tier': "modern_classic", 'listen_score': 98},
    {'artist': "Arcade Fire", 'song': "Wake Up", 'genre': "Indie Rock", 'year': 2004, 'acclaim': "Grammy winner, anthem of a generation", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "LCD Soundsystem", 'song': "All My Friends", 'genre': "Indie/Electronic", 'year': 2007, 'acclaim': "Pitchfork #1, critically adored", 'tier': "cult", 'listen_score': 96},
    {'artist': "Neutral Milk Hotel", 'song': "In the Aeroplane Over the Sea", 'genre': "Indie Folk", 'year': 1998, 'acclaim': "Cult classic, one of the most beloved indie albums", 'tier': "cult", 'listen_score': 97},
    {'artist': "Sufjan Stevens", 'song': "Casimir Pulaski Day", 'genre': "Indie Folk", 'year': 2005, 'acclaim': "Universally beloved indie masterpiece", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Talking Heads", 'song': "Once in a Lifetime", 'genre': "New Wave/Art Rock", 'year': 1980, 'acclaim': "RS 500, unique and influential", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Modest Mouse", 'song': "Float On", 'genre': "Indie Rock", 'year': 2004, 'acclaim': "Indie anthem, universally loved", 'tier': "modern_classic", 'listen_score': 95},
    {'artist': "The Strokes", 'song': "Reptilia", 'genre': "Indie Rock", 'year': 2003, 'acclaim': "RS 500, indie rock anthem", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Bon Iver", 'song': "Holocene", 'genre': "Indie Folk", 'year': 2011, 'acclaim': "Grammy winner, breathtaking", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "Vampire Weekend", 'song': "Oxford Comma", 'genre': "Indie Pop", 'year': 2008, 'acclaim': "Quirky indie classic", 'tier': "modern_classic", 'listen_score': 94},
    {'artist': "The Smiths", 'song': "There Is a Light That Never Goes Out", 'genre': "Indie Rock", 'year': 1986, 'acclaim': "RS 500, indie masterpiece", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Pixies", 'song': "Where Is My Mind?", 'genre': "Alternative Rock", 'year': 1988, 'acclaim': "RS 500, hugely influential", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Frank Ocean", 'song': "Nights", 'genre': "R&B", 'year': 2016, 'acclaim': "Genre-defining, critically acclaimed modern classic", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "D'Angelo", 'song': "Untitled (How Does It Feel)", 'genre': "Neo-Soul", 'year': 2000, 'acclaim': "Grammy winner, neo-soul masterpiece", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Erykah Badu", 'song': "Didn't Cha Know", 'genre': "Neo-Soul", 'year': 2000, 'acclaim': "Neo-soul classic, influential", 'tier': "modern_classic", 'listen_score': 95},
    {'artist': "Sade", 'song': "Smooth Operator", 'genre': "R&B/Soul", 'year': 1984, 'acclaim': "Timeless classic, iconic", 'tier': "classic", 'listen_score': 96},
    {'artist': "Solange", 'song': "Cranes in the Sky", 'genre': "R&B", 'year': 2016, 'acclaim': "Grammy winner, modern R&B masterpiece", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Anderson .Paak", 'song': "Come Down", 'genre': "R&B/Funk", 'year': 2016, 'acclaim': "Modern funk-soul masterpiece", 'tier': "modern_classic", 'listen_score': 95},
    {'artist': "Jill Scott", 'song': "Golden", 'genre': "Neo-Soul", 'year': 2000, 'acclaim': "Neo-soul classic, beloved", 'tier': "modern_classic", 'listen_score': 95},
    {'artist': "Maxwell", 'song': "Pretty Wings", 'genre': "Neo-Soul", 'year': 2009, 'acclaim': "Grammy winner, modern soul masterpiece", 'tier': "modern_classic", 'listen_score': 95},
    {'artist': "Al Green", 'song': "Let's Stay Together", 'genre': "Soul", 'year': 1971, 'acclaim': "RS 500, timeless soul classic", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Fela Kuti", 'song': "Water No Get Enemy", 'genre': "Afrobeat", 'year': 1975, 'acclaim': "Legendary Afrobeat pioneer, hugely influential", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Bob Marley", 'song': "No Woman, No Cry", 'genre': "Reggae", 'year': 1974, 'acclaim': "Reggae's most iconic song, 1B+ streams", 'tier': "legendary", 'listen_score': 98},
    {'artist': "David Bowie", 'song': "Heroes", 'genre': "Art Rock", 'year': 1977, 'acclaim': "RS 500, transcendent anthem", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Prince", 'song': "Purple Rain", 'genre': "Pop/Rock", 'year': 1984, 'acclaim': "RS 500, iconic masterpiece", 'tier': "legendary", 'listen_score': 99},
    {'artist': "Nirvana", 'song': "Smells Like Teen Spirit", 'genre': "Grunge/Rock", 'year': 1991, 'acclaim': "Defined a generation, RS 500", 'tier': "legendary", 'listen_score': 99},
    {'artist': "Björk", 'song': "Hyperballad", 'genre': "Art Pop/Electronic", 'year': 1995, 'acclaim': "Genre-defying masterpiece, critically adored", 'tier': "cult", 'listen_score': 96},
    {'artist': "The Velvet Underground", 'song': "Heroin", 'genre': "Art Rock", 'year': 1967, 'acclaim': "Influential beyond measure, RS 500", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Kate Bush", 'song': "Running Up That Hill", 'genre': "Art Pop", 'year': 1985, 'acclaim': "RS 500, 1B+ streams, Stranger Things revival", 'tier': "modern_classic", 'listen_score': 98},
    {'artist': "Talking Heads", 'song': "Burning Down the House", 'genre': "New Wave", 'year': 1983, 'acclaim': "RS 500, iconic new wave", 'tier': "classic", 'listen_score': 96},
    {'artist': "R.E.M.", 'song': "Losing My Religion", 'genre': "Alternative Rock", 'year': 1991, 'acclaim': "Grammy winner, RS 500", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "The Cure", 'song': "Just Like Heaven", 'genre': "Post-Punk/Dream Pop", 'year': 1987, 'acclaim': "RS 500, dream pop masterpiece", 'tier': "classic", 'listen_score': 96},
    {'artist': "Joy Division", 'song': "Love Will Tear Us Apart", 'genre': "Post-Punk", 'year': 1980, 'acclaim': "RS 500, iconic post-punk", 'tier': "legendary", 'listen_score': 98},
    {'artist': "New Order", 'song': "Blue Monday", 'genre': "Electronic/Dance", 'year': 1983, 'acclaim': "Best-selling 12-inch single of all time", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Depeche Mode", 'song': "Enjoy the Silence", 'genre': "Electronic/Synth-Pop", 'year': 1990, 'acclaim': "RS 500, synth-pop masterpiece", 'tier': "classic", 'listen_score': 96},
    {'artist': "Kraftwerk", 'song': "Autobahn", 'genre': "Electronic", 'year': 1974, 'acclaim': "Pioneered electronic music", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Brian Eno", 'song': "An Ending (Ascent)", 'genre': "Ambient", 'year': 1983, 'acclaim': "Defined ambient music, profoundly influential", 'tier': "cult", 'listen_score': 95},
    {'artist': "Aphex Twin", 'song': "Avril 14th", 'genre': "Electronic/Piano", 'year': 2001, 'acclaim': "Haunting piano piece, widely beloved", 'tier': "cult", 'listen_score': 95},
    {'artist': "Steve Reich", 'song': "Music for 18 Musicians", 'genre': "Minimalist/Classical", 'year': 1976, 'acclaim': "Minimalist masterpiece, revolutionary", 'tier': "cult", 'listen_score': 94},
    {'artist': "Philip Glass", 'song': "Metamorphosis One", 'genre': "Minimalist/Classical", 'year': 1988, 'acclaim': "Modern classical masterpiece", 'tier': "cult", 'listen_score': 95},
    {'artist': "Nusrat Fateh Ali Khan", 'song': "Allah Hoo", 'genre': "Qawwali/World", 'year': 1988, 'acclaim': "Legendary qawwali, transcendent", 'tier': "cult", 'listen_score': 97},
    {'artist': "Ali Farka Touré", 'song': "Ai Du", 'genre': "Malian Blues/World", 'year': 1994, 'acclaim': "African blues master, Grammy winner", 'tier': "cult", 'listen_score': 95},
    {'artist': "Buena Vista Social Club", 'song': "Chan Chan", 'genre': "Cuban Son/World", 'year': 1997, 'acclaim': "Revived Cuban music worldwide, Grammy winner", 'tier': "cult", 'listen_score': 96},
    {'artist': "Cesária Évora", 'song': "Sodade", 'genre': "Cape Verdean Morna/World", 'year': 1992, 'acclaim': "Barefoot diva, timeless", 'tier': "cult", 'listen_score': 95},
    {'artist': "Mulatu Astatke", 'song': "Yèkèrmo Sèw", 'genre': "Ethio-Jazz/World", 'year': 1974, 'acclaim': "Father of Ethio-jazz, unique sound", 'tier': "cult", 'listen_score': 94},
    {'artist': "Tom Waits", 'song': "Time", 'genre': "Experimental/Folk", 'year': 1985, 'acclaim': "One of the greatest songwriters", 'tier': "cult", 'listen_score': 96},
    {'artist': "Nick Cave", 'song': "Into My Arms", 'genre': "Alternative/Post-Punk", 'year': 1997, 'acclaim': "Haunting love song, critically adored", 'tier': "cult", 'listen_score': 96},
    {'artist': "Leonard Cohen", 'song': "Hallelujah", 'genre': "Folk/Singer-Songwriter", 'year': 1984, 'acclaim': "One of the most covered songs ever", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Joni Mitchell", 'song': "A Case of You", 'genre': "Folk/Singer-Songwriter", 'year': 1971, 'acclaim': "RS 500, songwriting at its peak", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Bob Dylan", 'song': "Like a Rolling Stone", 'genre': "Folk/Rock", 'year': 1965, 'acclaim': "RS 500 #1, changed songwriting forever", 'tier': "legendary", 'listen_score': 99},
    {'artist': "Simon & Garfunkel", 'song': "The Sound of Silence", 'genre': "Folk/Rock", 'year': 1964, 'acclaim': "Timeless, 1B+ streams, cultural touchstone", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Johnny Cash", 'song': "Hurt", 'genre': "Country/Folk", 'year': 2002, 'acclaim': "One of the greatest covers ever, Grammy winner", 'tier': "modern_classic", 'listen_score': 98},
    {'artist': "Patsy Cline", 'song': "Crazy", 'genre': "Country", 'year': 1961, 'acclaim': "Timeless country classic", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Hank Williams", 'song': "I'm So Lonesome I Could Cry", 'genre': "Country", 'year': 1949, 'acclaim': "RS 500, profoundly influential", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Miles Davis", 'song': "Blue in Green", 'genre': "Jazz", 'year': 1959, 'acclaim': "From Kind of Blue, the best-selling jazz album", 'tier': "legendary", 'listen_score': 98},
    {'artist': "John Coltrane", 'song': "A Love Supreme (Part 1)", 'genre': "Jazz", 'year': 1965, 'acclaim': "Spiritual jazz masterpiece", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Charles Mingus", 'song': "Goodbye Pork Pie Hat", 'genre': "Jazz", 'year': 1959, 'acclaim': "Jazz elegy, masterpiece", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Thelonious Monk", 'song': "'Round Midnight", 'genre': "Jazz", 'year': 1944, 'acclaim': "Most recorded jazz standard", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Billie Holiday", 'song': "Strange Fruit", 'genre': "Jazz/Vocal", 'year': 1939, 'acclaim': "One of the most powerful songs ever recorded", 'tier': "legendary", 'listen_score': 99},
    {'artist': "Ella Fitzgerald", 'song': "Summertime", 'genre': "Jazz/Vocal", 'year': 1968, 'acclaim': "Definitive version of the Gershwin classic", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Dizzy Gillespie", 'song': "A Night in Tunisia", 'genre': "Jazz", 'year': 1942, 'acclaim': "Bebop milestone", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Public Enemy", 'song': "Fight the Power", 'genre': "Hip-Hop", 'year': 1989, 'acclaim': "RS 500, most powerful hip-hop song", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Grandmaster Flash", 'song': "The Message", 'genre': "Hip-Hop", 'year': 1982, 'acclaim': "RS 500, changed hip-hop forever", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Run-DMC", 'song': "Walk This Way", 'genre': "Hip-Hop/Rock", 'year': 1986, 'acclaim': "Broke hip-hop into the mainstream", 'tier': "legendary", 'listen_score': 97},
    {'artist': "De La Soul", 'song': "Me Myself and I", 'genre': "Hip-Hop", 'year': 1989, 'acclaim': "Daisy Age, alternative hip-hop classic", 'tier': "classic", 'listen_score': 95},
    {'artist': "Gang Starr", 'song': "Moment of Truth", 'genre': "Hip-Hop", 'year': 1998, 'acclaim': "Underground hip-hop masterpiece", 'tier': "cult", 'listen_score': 96},
    {'artist': "Mos Def", 'song': "Mathematics", 'genre': "Hip-Hop", 'year': 1999, 'acclaim': "Conscious hip-hop at its finest", 'tier': "cult", 'listen_score': 95},
    {'artist': "The Roots", 'song': "The Seed (2.0)", 'genre': "Hip-Hop/Rock", 'year': 2002, 'acclaim': "Live band hip-hop, critically adored", 'tier': "cult", 'listen_score': 95},
    {'artist': "J Dilla", 'song': "Don't Cry", 'genre': "Hip-Hop/Instrumental", 'year': 2006, 'acclaim': "Producer genius, posthumous masterpiece", 'tier': "cult", 'listen_score': 96},
    {'artist': "Madonna", 'song': "Like a Prayer", 'genre': "Pop", 'year': 1989, 'acclaim': "RS 500, pop masterpiece", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Michael Jackson", 'song': "Billie Jean", 'genre': "Pop", 'year': 1983, 'acclaim': "RS 500, 1B+ streams, iconic", 'tier': "legendary", 'listen_score': 99},
    {'artist': "ABBA", 'song': "Dancing Queen", 'genre': "Pop", 'year': 1976, 'acclaim': "RS 500, euphoric pop perfection", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Kate Bush", 'song': "Wuthering Heights", 'genre': "Art Pop", 'year': 1978, 'acclaim': "Debut single, RS 500, utterly unique", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Cyndi Lauper", 'song': "Time After Time", 'genre': "Pop", 'year': 1984, 'acclaim': "RS 500, timeless pop classic", 'tier': "classic", 'listen_score': 97},
    {'artist': "Whitney Houston", 'song': "I Will Always Love You", 'genre': "Pop/R&B", 'year': 1992, 'acclaim': "Best-selling single by a female artist", 'tier': "legendary", 'listen_score': 98},
    {'artist': "George Michael", 'song': "Careless Whisper", 'genre': "Pop", 'year': 1984, 'acclaim': "RS 500, iconic sax riff", 'tier': "classic", 'listen_score': 97},
    {'artist': "Tears for Fears", 'song': "Everybody Wants to Rule the World", 'genre': "Pop/Rock", 'year': 1985, 'acclaim': "RS 500, 1B+ streams, timeless", 'tier': "classic", 'listen_score': 97},
    {'artist': "a-ha", 'song': "Take On Me", 'genre': "Pop/Synth-Pop", 'year': 1985, 'acclaim': "RS 500, iconic music video", 'tier': "classic", 'listen_score': 97},
    {'artist': "Peter Gabriel", 'song': "In Your Eyes", 'genre': "Pop/Rock", 'year': 1986, 'acclaim': "RS 500, beloved classic", 'tier': "classic", 'listen_score': 96},
    {'artist': "Paul Simon", 'song': "Graceland", 'genre': "World/Pop", 'year': 1986, 'acclaim': "Grammy winner, genre-blending masterpiece", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Tracy Chapman", 'song': "Fast Car", 'genre': "Folk/Pop", 'year': 1988, 'acclaim': "RS 500, timeless storytelling", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Sade", 'song': "By Your Side", 'genre': "R&B/Soul", 'year': 2000, 'acclaim': "Sophisticated soul, critically adored", 'tier': "classic", 'listen_score': 96},
    {'artist': "Lauryn Hill", 'song': "Ex-Factor", 'genre': "R&B/Hip-Hop", 'year': 1998, 'acclaim': "Grammy winner, RS 500, iconic", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "Erykah Badu", 'song': "On & On", 'genre': "Neo-Soul", 'year': 1997, 'acclaim': "Neo-soul landmark, iconic", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "D'Angelo", 'song': "Brown Sugar", 'genre': "Neo-Soul", 'year': 1995, 'acclaim': "Neo-soul foundation, groundbreaking", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Alicia Keys", 'song': "Fallin'", 'genre': "R&B/Soul", 'year': 2001, 'acclaim': "Grammy winner, iconic debut", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Mary J. Blige", 'song': "No More Drama", 'genre': "R&B/Hip-Hop", 'year': 2001, 'acclaim': "Queen of Hip-Hop Soul, Grammy winner", 'tier': "modern_classic", 'listen_score': 95},
    {'artist': "The Isley Brothers", 'song': "Footsteps in the Dark", 'genre': "R&B/Funk", 'year': 1977, 'acclaim': "Most sampled song in hip-hop history", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Curtis Mayfield", 'song': "Move On Up", 'genre': "Soul/Funk", 'year': 1970, 'acclaim': "RS 500, transcendent soul", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Sam Cooke", 'song': "A Change Is Gonna Come", 'genre': "Soul", 'year': 1964, 'acclaim': "RS 500, civil rights anthem", 'tier': "legendary", 'listen_score': 99},
    {'artist': "Otis Redding", 'song': "(Sittin' On) The Dock of the Bay", 'genre': "Soul", 'year': 1968, 'acclaim': "RS 500, timeless", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Aretha Franklin", 'song': "I Say a Little Prayer", 'genre': "Soul", 'year': 1968, 'acclaim': "RS 500, joyous perfection", 'tier': "legendary", 'listen_score': 97},
    {'artist': "The Temptations", 'song': "My Girl", 'genre': "Motown/Soul", 'year': 1964, 'acclaim': "RS 500, Motown at its best", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Marvin Gaye", 'song': "I Heard It Through the Grapevine", 'genre': "Soul", 'year': 1968, 'acclaim': "RS 500, iconic", 'tier': "legendary", 'listen_score': 97},
    {'artist': "James Brown", 'song': "Papa's Got a Brand New Bag", 'genre': "Funk", 'year': 1965, 'acclaim': "Birth of funk, RS 500", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Parliament", 'song': "Flash Light", 'genre': "Funk", 'year': 1977, 'acclaim': "P-Funk masterpiece, iconic bassline", 'tier': "cult", 'listen_score': 96},
    {'artist': "Sly and the Family Stone", 'song': "Family Affair", 'genre': "Funk/Soul", 'year': 1971, 'acclaim': "RS 500, groundbreaking", 'tier': "legendary", 'listen_score': 96},
    {'artist': "The Jackson 5", 'song': "I Want You Back", 'genre': "Motown/Pop", 'year': 1969, 'acclaim': "RS 500, joyful perfection", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Ramones", 'song': "Blitzkrieg Bop", 'genre': "Punk", 'year': 1976, 'acclaim': "Punk's theme song, RS 500", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Sex Pistols", 'song': "God Save the Queen", 'genre': "Punk", 'year': 1977, 'acclaim': "RS 500, punk landmark", 'tier': "legendary", 'listen_score': 96},
    {'artist': "The Clash", 'song': "London Calling", 'genre': "Punk/Rock", 'year': 1979, 'acclaim': "RS 500, genre-defying masterpiece", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Dead Kennedys", 'song': "Holiday in Cambodia", 'genre': "Hardcore Punk", 'year': 1980, 'acclaim': "Hardcore punk landmark, satirical genius", 'tier': "cult", 'listen_score': 96},
    {'artist': "Black Sabbath", 'song': "Iron Man", 'genre': "Heavy Metal", 'year': 1970, 'acclaim': "Invented heavy metal, RS 500", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Metallica", 'song': "Enter Sandman", 'genre': "Thrash Metal", 'year': 1991, 'acclaim': "Brought metal mainstream, Grammy winner", 'tier': "modern_classic", 'listen_score': 98},
    {'artist': "Slayer", 'song': "Raining Blood", 'genre': "Thrash Metal", 'year': 1986, 'acclaim': "Thrash metal landmark, iconic riff", 'tier': "cult", 'listen_score': 96},
    {'artist': "Opeth", 'song': "The Drapery Falls", 'genre': "Progressive Metal", 'year': 2001, 'acclaim': "Progressive metal masterpiece", 'tier': "cult", 'listen_score': 96},
    {'artist': "Mastodon", 'song': "Blood and Thunder", 'genre': "Progressive/Sludge Metal", 'year': 2004, 'acclaim': "Modern metal classic", 'tier': "cult", 'listen_score': 95},
    {'artist': "Gojira", 'song': "Flying Whales", 'genre': "Progressive/Death Metal", 'year': 2005, 'acclaim': "Modern metal landmark, environmental themes", 'tier': "cult", 'listen_score': 96},
    {'artist': "Meshuggah", 'song': "Bleed", 'genre': "Extreme/Technical Metal", 'year': 2008, 'acclaim': "Technical metal landmark, influential", 'tier': "cult", 'listen_score': 95},
    {'artist': "Tool", 'song': "Schism", 'genre': "Progressive Metal", 'year': 2001, 'acclaim': "Grammy winner, progressive metal landmark", 'tier': "cult", 'listen_score': 97},
    {'artist': "Rage Against the Machine", 'song': "Killing in the Name", 'genre': "Rap Metal/Rock", 'year': 1992, 'acclaim': "RS 500, politically charged landmark", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Nine Inch Nails", 'song': "Hurt", 'genre': "Industrial Rock", 'year': 1994, 'acclaim': "RS 500, industrial masterpiece", 'tier': "modern_classic", 'listen_score': 98},
    {'artist': "Radiohead", 'song': "Karma Police", 'genre': "Alternative Rock", 'year': 1997, 'acclaim': "RS 500, alt-rock landmark", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "Portishead", 'song': "Glory Box", 'genre': "Trip-Hop", 'year': 1994, 'acclaim': "Trip-hop landmark, RS 500", 'tier': "cult", 'listen_score': 97},
    {'artist': "Massive Attack", 'song': "Unfinished Sympathy", 'genre': "Trip-Hop", 'year': 1991, 'acclaim': "RS 500, trip-hop landmark", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Tricky", 'song': "Hell Is Round the Corner", 'genre': "Trip-Hop", 'year': 1995, 'acclaim': "Trip-hop landmark, influential", 'tier': "cult", 'listen_score': 95},
    {'artist': "Gorillaz", 'song': "Feel Good Inc.", 'genre': "Alternative/Electronic", 'year': 2005, 'acclaim': "Grammy winner, genre-blending phenomenon", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "The Streets", 'song': "Dry Your Eyes", 'genre': "UK Garage/Hip-Hop", 'year': 2004, 'acclaim': "UK garage landmark, critically adored", 'tier': "cult", 'listen_score': 95},
    {'artist': "Dizzee Rascal", 'song': "Bonkers", 'genre': "UK Garage/Grime", 'year': 2009, 'acclaim': "Grime landmark", 'tier': "cult", 'listen_score': 94},
    {'artist': "Sophie", 'song': "Immaterial", 'genre': "Hyperpop/Electronic", 'year': 2017, 'acclaim': "Hyperpop landmark, critically adored", 'tier': "cult", 'listen_score': 95},
    {'artist': "Death Grips", 'song': "The Fever (Aye Aye)", 'genre': "Experimental/Hip-Hop", 'year': 2012, 'acclaim': "Experimental hip-hop landmark", 'tier': "cult", 'listen_score': 94},
    {'artist': "Grimes", 'song': "Oblivion", 'genre': "Art Pop/Electronic", 'year': 2012, 'acclaim': "Pitchfork #1, visionary", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Lorde", 'song': "Royals", 'genre': "Art Pop", 'year': 2013, 'acclaim': "Grammy winner, songwriting phenomenon", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Billie Eilish", 'song': "Bad Guy", 'genre': "Alt Pop", 'year': 2019, 'acclaim': "Grammy winner, 2B+ streams, cultural phenomenon", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "FKA twigs", 'song': "Cellophane", 'genre': "Art Pop/Electronic", 'year': 2019, 'acclaim': "Critically adored, visionary", 'tier': "cult", 'listen_score': 96},
    {'artist': "Frank Ocean", 'song': "Thinkin Bout You", 'genre': "R&B", 'year': 2012, 'acclaim': "Modern R&B landmark", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "Solange", 'song': "Losing You", 'genre': "R&B/Art Pop", 'year': 2012, 'acclaim': "Critically adored", 'tier': "modern_classic", 'listen_score': 95},
    {'artist': "Childish Gambino", 'song': "Redbone", 'genre': "R&B/Funk", 'year': 2016, 'acclaim': "Grammy winner, 1B+ streams, timeless groove", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "Anderson .Paak", 'song': "Come Down", 'genre': "R&B/Funk", 'year': 2016, 'acclaim': "Modern funk-soul masterpiece", 'tier': "modern_classic", 'listen_score': 95},
    {'artist': "Tyler, The Creator", 'song': "See You Again", 'genre': "Hip-Hop/R&B", 'year': 2017, 'acclaim': "Grammy winner, genre-blending hit", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Mitski", 'song': "Nobody", 'genre': "Indie Rock", 'year': 2018, 'acclaim': "Universally loved indie anthem", 'tier': "modern_classic", 'listen_score': 95},
    {'artist': "Phoebe Bridgers", 'song': "Motion Sickness", 'genre': "Indie Rock", 'year': 2017, 'acclaim': "Indie landmark, critically adored", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Sufjan Stevens", 'song': "Mystery of Love", 'genre': "Indie Folk", 'year': 2017, 'acclaim': "Oscar-nominated, breathtaking", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "The National", 'song': "About Today", 'genre': "Indie Rock", 'year': 2004, 'acclaim': "Devastating indie masterpiece", 'tier': "cult", 'listen_score': 96},
    {'artist': "Arcade Fire", 'song': "Neighborhood #1 (Tunnels)", 'genre': "Indie Rock", 'year': 2004, 'acclaim': "Indie landmark, breathtaking debut", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "LCD Soundsystem", 'song': "Someone Great", 'genre': "Indie/Electronic", 'year': 2007, 'acclaim': "Critically adored, emotionally resonant", 'tier': "cult", 'listen_score': 97},
    {'artist': "Caribou", 'song': "Our Love", 'genre': "Electronic/Pop", 'year': 2014, 'acclaim': "Modern electronic pop classic", 'tier': "cult", 'listen_score': 95},
    {'artist': "Jamie xx", 'song': "The Rest Is Noise", 'genre': "Electronic", 'year': 2014, 'acclaim': "Modern electronic masterpiece", 'tier': "cult", 'listen_score': 96},
    {'artist': "Floating Points", 'song': "Anasickmodular", 'genre': "Electronic", 'year': 2015, 'acclaim': "Modern electronic virtuosity", 'tier': "cult", 'listen_score': 94},
    {'artist': "Oneohtrix Point Never", 'song': "Sticky Drama", 'genre': "Experimental Electronic", 'year': 2015, 'acclaim': "Experimental electronic landmark", 'tier': "cult", 'listen_score': 94},
    # Eurovision (user rates 87.3 avg)
    {'artist': "Loreen", 'song': "Euphoria", 'genre': "Eurovision", 'year': 2012, 'acclaim': "Eurovision 2012 winner, widely considered the best entry ever", 'tier': "modern_classic", 'listen_score': 98},
    {'artist': "ABBA", 'song': "Waterloo", 'genre': "Eurovision", 'year': 1974, 'acclaim': "Eurovision 1974 winner, launched global superstars", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Salvador Sobral", 'song': "Amar Pelos Dois", 'genre': "Eurovision", 'year': 2017, 'acclaim': "Eurovision 2017 winner, record 93% of final vote", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "Duncan Laurence", 'song': "Arcade", 'genre': "Eurovision", 'year': 2019, 'acclaim': "Eurovision 2019 winner, 1B+ streams", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Go_A", 'song': "SHUM", 'genre': "Eurovision", 'year': 2021, 'acclaim': "Ukrainian electro-folk, Eurovision cult hit", 'tier': "cult", 'listen_score': 95},
    {'artist': "Måneskin", 'song': "Zitti E Buoni", 'genre': "Eurovision/Rock", 'year': 2021, 'acclaim': "Eurovision 2021 winner, global rock phenomenon", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "Dana International", 'song': "Diva", 'genre': "Eurovision", 'year': 1998, 'acclaim': "Eurovision 1998 winner, iconic dance pop", 'tier': "classic", 'listen_score': 94},
    {'artist': "Alexander Rybak", 'song': "Fairytale", 'genre': "Eurovision/Folk", 'year': 2009, 'acclaim': "Eurovision 2009 winner, record 387 points", 'tier': "classic", 'listen_score': 95},
    # J-Pop/Anime (user has 410 songs)
    {'artist': "YOASOBI", 'song': "夜に駆ける (Yoru ni Kakeru)", 'genre': "J-Pop", 'year': 2019, 'acclaim': "Modern J-pop phenomenon, 300M+ streams", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "Ado", 'song': "うっせぇわ (Usseewa)", 'genre': "J-Pop", 'year': 2020, 'acclaim': "J-pop landmark, 200M+ streams, breakout hit", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Kenshi Yonezu", 'song': "Lemon", 'genre': "J-Pop", 'year': 2018, 'acclaim': "Best-selling digital single in Japan history", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "LiSA", 'song': "紅蓮華 (Gurenge)", 'genre': "J-Pop/Anime", 'year': 2019, 'acclaim': "Demon Slayer OP, J-pop landmark", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Eve", 'song': "廻廻奇譚 (Kaikai Kitan)", 'genre': "J-Pop/Rock", 'year': 2020, 'acclaim': "Jujutsu Kaisen OP, critically adored", 'tier': "modern_classic", 'listen_score': 95},
    {'artist': "Mariya Takeuchi", 'song': "プラスティック・ラブ (Plastic Love)", 'genre': "J-Pop/City Pop", 'year': 1984, 'acclaim': "City pop icon, 100M+ YouTube views", 'tier': "cult", 'listen_score': 97},
    # Classical
    {'artist': "Joe Hisaishi", 'song': "Merry-Go-Round of Life", 'genre': "Classical/Soundtrack", 'year': 2004, 'acclaim': "Howl's Moving Castle, orchestral masterpiece", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "Ludovico Einaudi", 'song': "Nuvole Bianche", 'genre': "Classical/Modern", 'year': 2004, 'acclaim': "Modern classical phenomenon, 500M+ streams", 'tier': "modern_classic", 'listen_score': 96},
    {'artist': "Max Richter", 'song': "On the Nature of Daylight", 'genre': "Classical/Modern", 'year': 2004, 'acclaim': "Used in Arrival, Shutter Island — profoundly moving", 'tier': "modern_classic", 'listen_score': 97},
    {'artist': "Ólafur Arnalds", 'song': "Near Light", 'genre': "Classical/Electronic", 'year': 2012, 'acclaim': "Neoclassical masterpiece, 200M+ streams", 'tier': "cult", 'listen_score': 95},
    {'artist': "Nils Frahm", 'song': "Says", 'genre': "Classical/Electronic", 'year': 2012, 'acclaim': "Modern classical experimental", 'tier': "cult", 'listen_score': 94},
    # Reggae/Dub (user's lowest rated genre at avg 45.2)
    {'artist': "Bob Marley & The Wailers", 'song': "Redemption Song", 'genre': "Reggae", 'year': 1980, 'acclaim': "One of the greatest songs ever written", 'tier': "legendary", 'listen_score': 99},
    {'artist': "Peter Tosh", 'song': "Legalize It", 'genre': "Reggae", 'year': 1976, 'acclaim': "Reggae landmark, iconic", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Toots and the Maytals", 'song': "Pressure Drop", 'genre': "Reggae/Ska", 'year': 1969, 'acclaim': "Reggae landmark, timeless", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Jimmy Cliff", 'song': "The Harder They Come", 'genre': "Reggae", 'year': 1972, 'acclaim': "Reggae landmark, iconic film", 'tier': "legendary", 'listen_score': 95},
    {'artist': "Burning Spear", 'song': "Marcus Garvey", 'genre': "Reggae", 'year': 1975, 'acclaim': "Roots reggae masterpiece", 'tier': "cult", 'listen_score': 95},
    {'artist': "Lee 'Scratch' Perry", 'song': "Roast Fish & Cornbread", 'genre': "Reggae/Dub", 'year': 1973, 'acclaim': "Dub pioneer, genius", 'tier': "cult", 'listen_score': 94},
    # Blues
    {'artist': "B.B. King", 'song': "The Thrill Is Gone", 'genre': "Blues", 'year': 1969, 'acclaim': "RS 500, blues at its peak", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Muddy Waters", 'song': "Mannish Boy", 'genre': "Blues", 'year': 1955, 'acclaim': "Delta blues landmark, iconic", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Robert Johnson", 'song': "Cross Road Blues", 'genre': "Blues", 'year': 1936, 'acclaim': "Foundational blues, legendary myth", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Howlin' Wolf", 'song': "Smokestack Lightning", 'genre': "Blues", 'year': 1956, 'acclaim': "Chicago blues landmark, iconic", 'tier': "legendary", 'listen_score': 95},
    {'artist': "John Lee Hooker", 'song': "Boom Boom", 'genre': "Blues", 'year': 1961, 'acclaim': "Blues landmark, iconic riff", 'tier': "legendary", 'listen_score': 95},
    # Country
    {'artist': "Dolly Parton", 'song': "Jolene", 'genre': "Country", 'year': 1973, 'acclaim': "RS 500, universally beloved", 'tier': "legendary", 'listen_score': 98},
    {'artist': "Johnny Cash", 'song': "Folsom Prison Blues", 'genre': "Country", 'year': 1955, 'acclaim': "RS 500, iconic", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Willie Nelson", 'song': "On the Road Again", 'genre': "Country", 'year': 1980, 'acclaim': "RS 500, timeless outlaw country", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Patsy Cline", 'song': "Crazy", 'genre': "Country", 'year': 1961, 'acclaim': "RS 500, timeless country classic", 'tier': "legendary", 'listen_score': 97},
    {'artist': "Hank Williams", 'song': "Your Cheatin' Heart", 'genre': "Country", 'year': 1953, 'acclaim': "RS 500, foundational country", 'tier': "legendary", 'listen_score': 96},
    {'artist': "Townes Van Zandt", 'song': "Pancho and Lefty", 'genre': "Country/Folk", 'year': 1972, 'acclaim': "Songwriting masterpiece, anthemic", 'tier': "cult", 'listen_score': 96},
]


# ============================================================
# Genre alias map — bridges classification genre names (e.g. "Rap/Hip-Hop")
# to challenge DB genre names (e.g. "Hip-Hop") so opposite-taste mode
# can correctly match your lowest-rated genres to challenge entries.
# ============================================================

GENRE_ALIAS_TO_CLASS: Dict[str, str] = {
    # Direct matches (identity aliases for safety)
    'Pop': 'Pop',
    'Rock': 'Rock',
    'Classic Rock': 'Rock',
    'Progressive Rock': 'Rock',
    'Art Rock': 'Rock',
    'Alternative Rock': 'Rock',
    'Indie Rock': 'Rock',
    'Grunge/Rock': 'Rock',
    'Punk/Rock': 'Rock',
    'Pop/Rock': 'Pop',
    'Rap Metal/Rock': 'Rap/Hip-Hop',
    'Classical/Instrumental': 'Classical/Instrumental',
    'Classical/Soundtrack': 'Classical/Instrumental',
    'Classical/Modern': 'Classical/Instrumental',
    'Classical/Electronic': 'Classical/Instrumental',
    'Minimalist/Classical': 'Classical/Instrumental',
    'Electronic/Dance': 'Electronic/Dance',
    'Electronic': 'Electronic/Dance',
    'Electronic/IDM': 'Electronic/Dance',
    'Electronic/Ambient': 'Electronic/Dance',
    'Electronic/Jazz': 'Electronic/Dance',
    'Electronic/House': 'Electronic/Dance',
    'Electronic/Piano': 'Electronic/Dance',
    'Electronic/Pop': 'Electronic/Dance',
    'Electronic/Synth-Pop': 'Electronic/Dance',
    'J-Pop': 'J-Pop/Anime',
    'J-Pop/Anime': 'J-Pop/Anime',
    'J-Pop/City Pop': 'J-Pop/Anime',
    'J-Pop/Rock': 'J-Pop/Anime',
    'Hip-Hop': 'Rap/Hip-Hop',
    'Hip-Hop/R&B': 'R&B/Soul',
    'Hip-Hop/Rock': 'Rock',
    'Hip-Hop/Instrumental': 'Rap/Hip-Hop',
    'Jazz/Swing': 'Jazz/Swing',
    'Jazz': 'Jazz/Swing',
    'Jazz/Vocal': 'Jazz/Swing',
    'Jazz/Funk': 'Disco/Funk',
    'Jazz/Soul': 'Jazz/Swing',
    'R&B/Soul': 'R&B/Soul',
    'R&B': 'R&B/Soul',
    'R&B/Hip-Hop': 'R&B/Soul',
    'R&B/Funk': 'R&B/Soul',
    'R&B/Art Pop': 'R&B/Soul',
    'Neo-Soul': 'R&B/Soul',
    'Soul': 'R&B/Soul',
    'Funk': 'Disco/Funk',
    'Funk/Soul': 'R&B/Soul',
    'Folk/Singer-Songwriter': 'Folk/Acoustic',
    'Folk/Rock': 'Folk/Acoustic',
    'Folk/Acoustic': 'Folk/Acoustic',
    'Folk/Pop': 'Pop',
    'Folk': 'Folk/Acoustic',
    'Indie/Alternative': 'Indie/Alternative',
    'Indie/Electronic': 'Electronic/Dance',
    'Indie': 'Indie/Alternative',
    'Indie Folk': 'Folk/Acoustic',
    'Indie Rock': 'Rock',
    'Indie Pop': 'Pop',
    'Country/Folk': 'Folk/Acoustic',
    'Country': 'Country',
    'Metal': 'Metal',
    'Heavy Metal': 'Metal',
    'Thrash Metal': 'Metal',
    'Progressive Metal': 'Metal',
    'Progressive/Sludge Metal': 'Metal',
    'Progressive/Death Metal': 'Metal',
    'Extreme/Technical Metal': 'Metal',
    'Industrial Rock': 'Rock',
    'Pop': 'Pop',
    'Alt Pop': 'Pop',
    'Art Pop': 'Pop',
    'Art Pop/Electronic': 'Electronic/Dance',
    'Punk': 'Punk',
    'Hardcore Punk': 'Punk',
    'Post-Punk/Dream Pop': 'Punk',
    'Post-Punk': 'Punk',
    'Punk/Rock': 'Rock',
    'Reggae/Dub': 'Reggae/Dub',
    'Reggae': 'Reggae/Dub',
    'Reggae/Ska': 'Reggae/Dub',
    'Blues': 'Blues',
    'Disco/Funk': 'Disco/Funk',
    'Latin': 'Latin',
    'Eurovision': 'Eurovision',
    'Eurovision/Rock': 'Rock',
    'Eurovision/Folk': 'Folk/Acoustic',
    'K-Pop': 'K-Pop',
    'A Cappella': 'A Cappella',
    'Soundtrack/Score': 'Soundtrack/Score',
    'Trip-Hop': 'Electronic/Dance',
    'Ambient': 'Electronic/Dance',
    'Afrobeat': 'Electronic/Dance',
    'Qawwali/World': 'World',
    'Malian Blues/World': 'World',
    'Cuban Son/World': 'World',
    'Cape Verdean Morna/World': 'World',
    'Ethio-Jazz/World': 'World',
    'World/Pop': 'Pop',
    'New Wave/Art Rock': 'Rock',
    'New Wave': 'Rock',
    'Experimental/Folk': 'Folk/Acoustic',
    'Experimental/Electronic': 'Electronic/Dance',
    'Experimental/Hip-Hop': 'Rap/Hip-Hop',
    'Industrial Rock': 'Rock',
    'Hyperpop/Electronic': 'Electronic/Dance',
    'Alternative': 'Indie/Alternative',
    'Alternative/Post-Punk': 'Punk',
    'Alternative/Electronic': 'Electronic/Dance',
    'UK Garage/Hip-Hop': 'Electronic/Dance',
    'UK Garage/Grime': 'Electronic/Dance',
    'Post-Punk/Dream Pop': 'Punk',
    'Motown/Pop': 'Pop',
    'Motown/Soul': 'R&B/Soul',
    'Christmas/Holiday': 'Christmas/Holiday',
    'Anime Rock': 'J-Pop/Anime',
    'J-Pop/Anime': 'J-Pop/Anime',
}
